### ISSUE TITLE
map attribution hidden by deckgl drawings

### ISSUE THREAD

**Issue by jonenst** [visgl/deck.gl#5337] opened 2021-01-15 15:59 UTC
#### Description

Map attribution is hidden by deckgl polygons
#### Expected Behavior

Map attribution is always visible

#### Repro Steps

https://deck.gl/examples/geojson-layer-polygons/
pan the window so that the polygons are at the bottom right corner and see the attribution becoming hidden

The controls are in the stacking context of the static map which has z-index:-1 so nothing can put them over the deckgl overlay canvas 

#### Environment
 - Framework Version: deck.gl 8.3.0
 - Browser Version: all
 - OS: all

**Comment by Pessimistress** [comment] 2021-01-15 16:29
Duplicate of #4165

**Closed by Pessimistress** 2021-01-15 16:29 UTC
Labels: bug

**Comment by Pessimistress** [comment] 2021-01-23 00:49
Solution https://github.com/visgl/deck.gl/issues/4165#issuecomment-765803011
