### ISSUE TITLE
pydeck: PathLayer fails when input data contains a 0-length line

### ISSUE THREAD

**Issue by tamir-jether** [visgl/deck.gl#4627] opened 2020-05-31 11:27 UTC
#### Description
When trying to create a path layer, if the dataframe contain a path location of x->y, where x and y have the same location, instead of "ignoring" that specific path, the entire layer is corrupted.
It will cause the paths in the layer to act as one path.

#### Repro Steps
In order to reproduce, i just used the example of the path layer, and change the path location of one item:

```python
import pydeck
import pandas as pd

DATA_URL = "https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/bart-lines.json"
df = pd.read_json(DATA_URL)


def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i : i + 2], 16) for i in (0, 2, 4))


df["color"] = df["color"].apply(hex_to_rgb)

**df['path'][0] = [[0, 1], [0, 1]]**

view_state = pydeck.ViewState(latitude=37.782556, longitude=-122.3484867, zoom=10)

layer = pydeck.Layer(
    type="PathLayer",
    data=df,
    pickable=True,
    get_color="color",
    width_scale=20,
    width_min_pixels=2,
    get_path="path",
    get_width=5,
)

r = pydeck.Deck(layers=[layer], initial_view_state=view_state, tooltip={"text": "{name}"})
r.to_html("path_layer.html",open_browser=True, notebook_display=False)
```

**Comment by ajduberstein** [comment] 2020-06-05 20:36
The stopgap here would be to filter out 0-length lines in the source data, though I agree this is not a great user experience. Let me look into alternatives.

**Comment by Pessimistress** [comment] 2020-06-05 20:51
PathLayer does filter out invalid paths: https://codepen.io/Pessimistress/pen/OJMJoJX

**Comment by MGraefe** [comment] 2020-07-15 13:15
@Pessimistress We ran into a problem that the layer would render all paths in the same color despite every path having a unique color. This is related to #4208 but the problem wasn't properly reproduced there.

The issue appears if the very first path is invalid. Any invalid path that is not the very first one in the list is properly ignored. But not the very first one.

The following codepen shows the issue: https://codepen.io/mgraefe/pen/BajOyBE
The lines should be red and blue but they're green because the very first element is green but its path is invalid. You can comment the very first invalid path out and 'comment in' the one in between and everything is okay.

Now of course one can say that it's normal for the PathLayer to show undefined behaviour if invalid paths are given to it. And in fact the PathLayer is already pretty robust, how it ignores invalid paths under normal circumstances. The first one being invalid is a rather odd edge case that doesn't need to be fixed IMHO.

We just worked around this behaviour by filtering out paths that have less than two elements. I just hope this helps clearing up the situation.

**Comment by Pessimistress** [comment] 2020-07-17 17:14
Fixed in `deck.gl@8.2.3`.

**Comment by Pessimistress** [comment] 2020-07-24 20:32
pydeck 0.4.0

**Comment by ajduberstein** [comment] 2020-07-24 20:32
Fixed–thank you @Pessimistress

pydeck 0.3.1 (locked to deck.gl 8.1)

![image](https://user-images.githubusercontent.com/2204757/88432933-0598e380-cdb2-11ea-8be5-e895fc5cc141.png)

pydeck 0.4.0 (locked to deck.gl 8.2)

![image](https://user-images.githubusercontent.com/2204757/88432969-15182c80-cdb2-11ea-90da-b74f5a2c3ff0.png)

**Closed by Pessimistress** 2020-07-24 20:32 UTC
Labels: bug, pydeck
