### ISSUE TITLE
[Bug] Mismatch rendering basemap and layer after refresh

### ISSUE THREAD

**Issue by dominik-visca** [visgl/deck.gl#8171] opened 2023-10-05 07:32 UTC
### Description

I am currently trying to use Deck.GL with react-map-gl and MapLibre. The beginning has worked fine, for integrating the NavigationalControl I then included the MapboxOverlay. Unfortunately, this has led to the overlay and the basemap sometimes (especially after a page refresh) not being on top of each other. Most of the time I even have problems displaying the correct representation at all. 

The property "interleaved" leads to the fact that the overlay and basemap lie on top of each other, but the lower half of the screen is completely gray.

Example screenshots are below:

![bug_refresh_interleaved](https://github.com/visgl/deck.gl/assets/94321642/ca5fc264-44e3-4b0a-84b9-3dacce7e460b)
Grey part at the bottom; interleaved: true

![bug_refresh_not_interleaved](https://github.com/visgl/deck.gl/assets/94321642/2975dec1-79f8-4689-b61b-accf5a373dd1)
Grey part at the bottom, mismatch between basemap and layer; interleaved: false

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

Code of my MapContainer.jsx

```javascript
import React, { useState } from 'react';
import {MapboxOverlay} from '@deck.gl/mapbox';
import maplibregl from 'maplibre-gl';
import {useControl} from 'react-map-gl';
import { Map as MapGL, NavigationControl } from 'react-map-gl/maplibre';

import Popup from './Popup.jsx';

function DeckGLOverlay(props) {
    const overlay = useControl(() => new MapboxOverlay(props));
    overlay.setProps(props);
    return null;
}

const MapContainer = ({ initialViewState, layers, mapStyle }) => {
    const [selectedFeature, setSelectedFeature] = useState(null);
    const [popupPosition, setPopupPosition] = useState({ x: 0, y: 0 });
    const handleClick = (event) => {
        setSelectedFeature(event.object);
        setPopupPosition({ x: event.x, y: event.y });
    }

    return (
        <>
            <MapGL
                reuseMaps
                mapLib={maplibregl}
                mapStyle={mapStyle}
                width="100%"
                height="100%"
                initialViewState={initialViewState}
                controller={true}

            >
                <DeckGLOverlay
                    layers={layers}
                    interleaved={false}
                    onClick={handleClick}
                />
                <NavigationControl />
            </MapGL>
            {selectedFeature && <Popup feature={selectedFeature} position={popupPosition} />}
        </>

    );
};

export default MapContainer;
```

### Environment

- Framework version: deck.gl@8.9.30, react-map-gl@7.1.6
- Browser: Firefox or Chromium-based
- OS: MacOS

**Comment by Pessimistress** [comment] 2023-10-05 08:54
width and height are not valid props, see https://visgl.github.io/react-map-gl/docs/api-reference/map

You can find a working example at https://github.com/visgl/react-map-gl/blob/master/examples/deckgl-overlay/src/app.tsx

If you still believe there is a bug, please create a CodeSandbox that reproduces your issue.

**Comment by dominik-visca** [comment] 2023-10-05 09:33
Removing width and height does not solve the problem. But opening and closing the developer tools (and forcing a resizing) fixes a existing mismatch. I try to create a CodeSandbox with my setup.

**Comment by dominik-visca** [comment] 2023-10-05 17:44
Unfortunately, I was not able to reproduce the error in a CodeSandbox... What I noticed though: The canvas element is assigned a height of 300px, no matter how big the screen is. If I do a resize trigger (e.g. by resizing the window or opening Developer Tools, then the 300px value jumps to the appropriate one to fill the entire viewport. Where does this "seemingly" arbitrary height value of 300px come from? And why does this canvas element have two different height and width properties? Where do those canvas properties come from?

![bug_canvas_height](https://github.com/visgl/deck.gl/assets/94321642/470f4ff4-1996-40fd-bf53-8bb71464fdb8)

**Comment by Pessimistress** [comment] 2023-10-05 17:54
The canvas is created by maplibre-gl. I suspect your issue is that the container of your map does not have a defined height, therefore the resolution of `height: 100%` is ambiguous.

Closing the issue for now since it doesn't seem related to deck.gl. Feel free to reopen if you are able to reproduce.

**Closed by Pessimistress** 2023-10-05 17:54 UTC
Labels: bug

**Comment by dominik-visca** [comment] 2023-10-05 18:13
This was the necessary hint, thank you! 300px is the standard height if maplibre/mapbox has no height information.
