### ISSUE TITLE
SceneGraphLayer animation

### ISSUE THREAD

**Issue by grahambates-sp** [visgl/deck.gl#3752] opened 2019-10-07 10:47 UTC
There is a lovely example of SceneGraphLayer in the examples folder, but when I replace the plane .glb file with one that has an animation defined, it doesnt seem to animate, despite the presence of a code block that plays all animations at speed factor 1.

I am currently using the monster.glb file found here -

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Monster

Is this a problem with the source .glb files or do SceneGraph animations not work at the moment?

**Comment by 1chandu** [comment] 2019-10-07 16:36
CC: @ibgreen  @jianhuang01

**Comment by ibgreen** [comment] 2019-10-07 17:32
@grahambates - Thanks for reporting. We currently have only partial support for glTF animations. We do not support skin/joint/morph target type animations, just simple transform interpolations.

Implementing support for those should not be overly hard, but is currently not planned. 

Until we implement this, we should document this limitation somewhere.

@georgios-uber

**Comment by Pessimistress** [comment] 2020-10-16 18:21
While unlikely the cause of the original issue, animation was broken in v8. A fix has been published in 8.3.1, [demo](https://deck.gl/docs/api-reference/mesh-layers/scenegraph-layer)

**Closed by Pessimistress** 2020-10-16 18:21 UTC
Labels: question

**Comment by xiemeilong** [comment] 2020-12-14 05:01
This limitation is still not documented .

**Comment by mogmog** [comment] 2021-04-07 19:51
Has there been any developments on this? It would be amazing to support the skin/joint/morph target type animations.

**Comment by ibgreen** [comment] 2021-04-07 20:00
@mogmog No activity on the morph-target type of animations, but we would be very supportive if a contributor expressed interest in this (alternatively this could also be accelerated if someone provided modest funding through the vis.gl open governance model via UCF / Linux Foundation).

Note that there are some discussions around data driven animations in the `ScenegraphLayer`, but these are still basic scene graph animations, not related to morph targets.
