### ISSUE TITLE
Symbols on line layer.

### ISSUE THREAD

**Issue by UttamRahane** [visgl/deck.gl#4724] opened 2020-06-25 15:41 UTC
Is there any way to add symbols/icons on line?  I'm looking something like 
[https://docs.mapbox.com/mapbox-gl-js/example/animate-point-along-route/](url)

with some following properties 
layout: {
                'icon-image': 'oneway-large',
                'icon-rotate': 0,
                'icon-rotation-alignment': 'map',
                'icon-allow-overlap': true,
                'icon-size': 1.5,
                'icon-ignore-placement': true,
                'symbol-placement': 'line-center',
            },

**Comment by Pessimistress** [comment] 2020-11-24 17:28
Duplicate of #4199

**Closed** 2020-11-24 17:28 UTC
Labels: question
