### ISSUE TITLE
Controller not working in multiple views

### ISSUE THREAD

**Issue by sumarlidason** [visgl/deck.gl#5903] opened 2021-06-22 18:34 UTC
#### Description
unable to grab/pan when using `ContextProvider={MapContext.Provider}` since `8.4.17`; deckgl stuck in "drag state" as indicated by cursor. Zoom still functions & resets cursor. On drag only the first even fires.

_Also_, let me know if I've taken a wrong turn or misusing the components. 🤗 

#### Expected Behavior
normal map movement pan/zoom functionality

#### Repro Steps
minimal reproducible project @ https://github.com/sumarlidason/deckgl-controller-issue

#### Environment
 - Framework Version: 8.4.17
 - React-Map-GL: 6.1.16
 - Browser Version: 91.0.4472.106
 - OS: macOS 11.4 (20F71) [intel / Radeon Pro 560X]

**Comment by Pessimistress** [comment] 2021-06-22 18:47
What was the last version that worked for you?

**Comment by Pessimistress** [comment] 2021-06-22 18:50
`onViewStateChange` is a Deck prop, it does not exist on View.

**Comment by sumarlidason** [comment] 2021-06-22 19:00
the previous dot version works: `8.4.16`

if you run `yarn add @deck.gl/aggregation-layers@8.4.16 @deck.gl/core@8.4.16 @deck.gl/extensions@8.4.16 @deck.gl/geo-layers@8.4.16 @deck.gl/google-maps@8.4.16 @deck.gl/json@8.4.16 @deck.gl/layers@8.4.16 @deck.gl/mapbox@8.4.16 @deck.gl/mesh-layers@8.4.16 @deck.gl/react@8.4.16` in the sample project ~ pan/zoom works normally.

I took a quick look at the [diff](https://github.com/visgl/deck.gl/compare/v8.4.16...v8.4.17#diff-3355ec5def1bafb0978c41d8b8d0926f83e5e20e53c1cc853ca54a6345f62b81L295) and saw changes to view controllers. Was hoping you knew what happened ~

**Comment by mcost45** [comment] 2021-06-24 13:59
@Pessimistress I've encountered the same problem:, .17 boken pan, but it works in .16.

I noticed it seemed to be related in particular to broken view state transitions - I could not pan by mouse, but arrow keys would work by 'snapping' to the next position, when it would normally be smooth.

**Comment by Pessimistress** [comment] 2021-06-24 17:08
Looks like the issue is present when using multi-view and only some of the views enable controllers. I'll put up a fix.

**Comment by Pessimistress** [comment] 2021-06-24 18:01
This should be fixed in 8.4.18.

**Comment by mcost45** [comment] 2021-06-25 12:06
Yep it's fixed thanks!

**Closed** 2021-06-25 12:30 UTC
Labels: bug

**Comment by sumarlidason** [comment] 2021-06-25 15:46
thanks for the quick turn @Pessimistress ! 😈
