### ISSUE TITLE
How to set deckgl layer over google polygon

### ISSUE THREAD

**Issue by benderlidze** [visgl/deck.gl#4663] opened 2020-06-09 13:50 UTC
I want to set deckgl ScatterplotLayer over bermudaTriangle polygon. I tried to change layers order in the code but with no luck. Is there a way to do this? Thanks. Here is my code

```
 var triangleCoords = [
                    { lat: 38.737066, lng: -92.540693 },
                    { lat: 36, lng: -93 },
                    { lat: 35, lng: -95 },
                    { lat: 38, lng: -92 },
                ];

                // Construct the polygon.
                var bermudaTriangle = new google.maps.Polygon({
                    paths: triangleCoords,
                    strokeColor: '#FF0000',
                    strokeOpacity: 0.8,
                    strokeWeight: 2,
                    fillColor: '#FF0000',
                    fillOpacity: 0.35
                });
                bermudaTriangle.setMap(map);

                pins = new deck.ScatterplotLayer({
                    id: 'scatterplot-layer',
                    data: geojson.features,
                    getPosition: d => {
                        return d.geometry.coordinates
                    },
                    pickable: true,
                    opacity: 1,
                    stroked: true,
                    filled: true,
                    radiusScale: 10,
                    radiusMinPixels: 5,
                    radiusMaxPixels: 5,
                    getFillColor: d => [255, 0, 0],
                    visible: true,
                });

                deckOverlay = new deck.GoogleMapsOverlay({
                    layers: [pins]
                });
                deckOverlay.setMap(map);
```

**Comment by grant007** [comment] 2020-07-03 12:37
I have a similar question with two parts. 1) Deck.gl objects within/under Google Maps polygon where not interactive i.e. pickable, onHover, onClick. 2) How to make Deck.gl objects appear visually on top of Google Maps polygon. 

I found a solution to my problem #1 by setting Google Maps polygon's option _{clickable: false}_ enabled deck.gl's object to be interactive.

I have not found a solution to my problem #2.

**Comment by Pessimistress** [comment] 2020-07-06 20:57
Possible duplicate of https://github.com/visgl/deck.gl/issues/3616

**Comment by Pessimistress** [comment] 2020-10-06 18:07
In `8.3.0-beta.1` you can control the z-index of the deck.gl canvas:

```js
const overlay = new GoogleMapsOverlay({
    layers: [],
    style: {zIndex: 10}
  })
```

**Closed** 2020-10-22 01:12 UTC
Labels: question
