### ISSUE TITLE
Build fails with Vite

### ISSUE THREAD

**Issue by clarknova** [visgl/deck.gl#6134] opened 2021-08-26 08:33 UTC
#### Description
Build fails with Vite
#### Expected Behavior
Build does not fail
#### Repro Steps
npm install deck.gl
use it

#### Environment
 - Framework Version: 8.4.13
 - Browser Version: Chrome 92
 - OS:  Windows 10

#### Logs
```
buffer.js:39 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at buffer.js:39
(anonymous) @ buffer.js:39
```

**Comment by clarknova** [comment] 2021-08-30 06:29
I constructed a mimimal Repo that crashes with the newest version of deck.gl, vite and react
https://github.com/clarknova/deck.gl-vite-minimal-example/tree/main

**Comment by ilan-gold** [comment] 2021-08-30 10:15
cc: @manzt if you're interested 
Thanks @clarknova for posting.

**Comment by ilan-gold** [comment] 2021-08-30 15:53
Playing a bit of whack-a-mole @clarknova but https://github.com/visgl/loaders.gl/pull/1816 is a first step, I think.  This is not my expertise though.

**Comment by manzt** [comment] 2021-08-30 21:52
Is there a reason you have added an `exclude` entry for `@deck.gl/layers` in your `vite.config.js`? This prevents esbuild from prebundling that module, which works out of the box.

**Comment by clarknova** [comment] 2021-08-31 06:29
I added it because i was getting this error
`buffer.js:39 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at buffer.js:39
(anonymous) @ buffer.js:39`
so i turned off every kind of optimization hoping that would resolve the issue.

**Comment by Pessimistress** [comment] 2021-08-31 19:18
I believe this is caused by some circular dependency references in luma.gl. Opened an issue here: https://github.com/visgl/luma.gl/issues/1493

**Comment by Pessimistress** [comment] 2021-09-08 16:41
This should be fixed in `@luma.gl/webgl@8.5.7`. You may need to remove the lock file and reinstall dependencies.

**Comment by ibgreen** [comment] 2021-09-08 18:22
Assigned 8.6 milestone to make sure we also fix on master. Let's keep this ticket open.

**Comment by Pessimistress** [comment] 2021-09-21 19:28
@ibgreen We will use the issue in luma.gl to track remaining work items.

**Closed by Pessimistress** 2021-09-21 19:28 UTC
Labels: bug

**Comment by JannikGM** [comment] 2022-08-01 12:41
We still had issues with deck.gl 8.8.x.

We work around problems with these vite settings:

```js
import { defineConfig } from 'vite'
import { viteCommonjs } from '@originjs/vite-plugin-commonjs'
const path = require('path')

// Plugin to spoof an empty module
function stubPlugin(virtualModuleId) {
  const resolvedVirtualModuleId = '\0' + virtualModuleId
  return {
    name: 'stub-plugin',
    resolveId(id) {
      return (id === virtualModuleId) ? resolvedVirtualModuleId : undefined
    },
    load(id) {
      return (id === resolvedVirtualModuleId) ? '' : undefined
    }
  }
}

export default defineConfig({
  plugins: [
    // [...]
    viteCommonjs(),
    // @probe.gl/log (dependency for deck.gl) internally does a dynamic require which is supposed to fail.
    // See https://github.com/uber-web/probe.gl/blob/7734e0158c9af9d6debcd6c7ed1869c21654a40b/modules/log/src/log.ts#L431
    stubPlugin('asciify-image')
  ],
  define: {
    // [...]
    // Hack for https://github.com/browserify/node-util/blob/6b828255a7f407efcd7e4d2c54ddb43256e491fb/util.js#L109
    'process.env': {}
  },
  // [...]
})
```

Note: We only ever use vite for development, and we use webpack for production. So this code path isn't tested very much.
