### ISSUE TITLE
Random lines appearing on TileLayer from @deck.gl/geo-layers

### ISSUE THREAD

**Issue by Martizs** [visgl/deck.gl#3824] opened 2019-10-30 16:46 UTC
#### Description
So i'm using react and i'm trying to load vector tiles(.mbtiles) to deck GL using the 'TileLayer' but random lines keep appearing on the layers when they are rendered, the same mbtiles file seems to be loading properly when using - https://github.com/mapbox/mbview . I'm using a tile server similar to this - https://gist.github.com/manuelroth/8c03fe64bb2926e7f96e688c6bb1353c to serve the tiles to the frontend. To create these tiles depending on the xyz i use '@mapbox/mbtiles' opposed to just 'mbtiles' shown in that ^ server file. And i'm also using the 'StaticMap' from 'react-map-gl' to load in the base map style.

Here is the snippet for serving the mbtiles:
```
const MBTiles = require('@mapbox/mbtiles');

// Enable CORS and set correct mime type/content encoding
const header = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers':
    'Origin, X-Requested-With, Content-Type, Accept',
  'Content-Type': 'application/x-protobuf',
  'Content-Encoding': 'gzip'
};

// Route which handles requests like the following: /<mbtiles-name>/0/1/2.pbf
router.get('/mbtiles/:z/:x/:y.*', (req, res) => {
  const fullPath = path.join(__dirname, '/static/geo_test.mbtiles');

  new MBTiles(fullPath, (err, mbtiles) => {
    mbtiles.getTile(
      req.params.z,
      req.params.x,
      req.params.y,
      (tileErr, tile, headers) => {
        if (tileErr) {
          res.set({ 'Content-Type': 'text/plain' });
          res.status(404).send('Tile rendering error: ' + tileErr + '\n');
        } else {
          res.set(header);
          res.send(tile);
        }
      }
    );
    if (err) console.log('error opening database');
  });
});
```

Here is the snippet for the frontend:
```
import React, { Component } from 'react';
import { LinearInterpolator, StaticMap } from 'react-map-gl';
import MAP_STYLE from 'components/GeoMap/data/map-style-basic-v8';
import DeckGL from '@deck.gl/react';
import { TileLayer } from '@deck.gl/geo-layers';
import { VectorTile } from '@mapbox/vector-tile';
import Protobuf from 'pbf';

const MAPBOX_TOKEN = process.env.REACT_APP_MAPBOX_TOKEN;

export class DeckGlTest extends Component {
  render() {
    const viewport = {
      latitude: 15,
      longitude: 0,
      zoom: 2,
      transitionInterpolator: new LinearInterpolator(),
      transitionDuration: 1000
    };

    const tileLayer = new TileLayer({
      stroked: true,
      pickable: true,

      getLineColor: [0, 128, 239],
      getFillColor: [255, 255, 255],

      opacity: 0.2,

      maxZoom: 11,

      getLineWidth: () => {
        return 1;
      },
      lineWidthMinPixels: 1,

      getTileData: ({ x, y, z }) => {
        const mapSource = `/api/mbtiles/${z}/${x}/${y}.pbf`;
        return fetch(mapSource)
          .then(response => {
            if (response.status === 200) {
              return response.arrayBuffer();
            }
            return null;
          })
          .then(buffer => {
            if (buffer) {
              const tile = new VectorTile(new Protobuf(buffer));
              const features = [];
              for (const layerName in tile.layers) {
                const vectorTileLayer = tile.layers[layerName];
                for (let i = 0; i < vectorTileLayer.length; i += 1) {
                  const vectorTileFeature = vectorTileLayer.feature(i);
                  const feature = vectorTileFeature.toGeoJSON(x, y, z);
                  features.push(feature);
                }
              }
              return features;
            }
            return [];
          });
      },

      onHover: ({ object }) => {
        console.log('hover object.properties', object && object.properties);
      }
    });

    return (
      <div>
        <DeckGL initialViewState={viewport} controller layers={[tileLayer]}>
          <StaticMap mapboxApiAccessToken={MAPBOX_TOKEN} mapStyle={MAP_STYLE} />
        </DeckGL>
      </div>
    );
  }
}

export default DeckGlTest;
```
Here is the mbtiles file i'm trying to load/serve - https://drive.google.com/file/d/1gQTdjJ6bbP6cFIYFrcgTc9WhP2uu0i-J/view?usp=sharing

Here's a snapshot of how its rendered: 
https://drive.google.com/file/d/1ttx3jxGAUTxCTDK-QpqDIVuy2PL_Xz8L/view?usp=sharing

Also: 
I seem to be getting some 404 not found errors for some mbtile xyz requests 

#### Repro Steps
1) Set up a React project with express js. 
2) Set up the frontend as shown in the above snippet ^
3) Set up nodejs with express to serve the mbtiles file as explained above ^
4) Run it. 
Mbtiles file: https://drive.google.com/file/d/1gQTdjJ6bbP6cFIYFrcgTc9WhP2uu0i-J/view?usp=sharing

#### Environment (please complete the following information):
 - Framework Version: deck.gl 7.3.3
 - Browser Version: Chrome 72.0
 - OS: Ubuntu 16.04.6 LTS xenial.

#### Logs
As mentioned above there are some 404 not found errors in the console, for some xyz tile requests:
DeckGl.js:40 GET http://localhost:3000/api/mbtiles/2/0/0.pbf 404 (Not Found)
DeckGl.js:40 GET http://localhost:3000/api/mbtiles/2/1/0.pbf 404 (Not Found)
DeckGl.js:40 GET http://localhost:3000/api/mbtiles/2/2/0.pbf 404 (Not Found)
DeckGl.js:40 GET http://localhost:3000/api/mbtiles/2/3/0.pbf 404 (Not Found)

**Comment by drewgoodwin2** [comment] 2019-11-01 23:32
I'm having the same issue. It seems like a problem with clipped features that overlap tile boundaries. The extra lines are sort of grid-like and they only appear on top of features.

In mapbox gl js: 
![good](https://user-images.githubusercontent.com/17484670/68061999-9afcc080-fcd5-11e9-9af3-a49f2b7dc7a3.png)

Using tile layer: 
![bad](https://user-images.githubusercontent.com/17484670/68062027-b5cf3500-fcd5-11e9-9c7e-5545ad2114a3.png)

**Comment by Pessimistress** [comment] 2019-11-05 21:29
This is because `PolygonLayer` (rendered by `GeoJsonLayer`) normalizes polygons by automatically closing all loops. This behavior makes sure that we render consistently when using irregular input. In the mapbox tiles case, you actually don't want the polygon "closed" where it is split at tile boundaries.

A workaround could be adding an option to `PolygonLayer` (and by extension `GeoJsonLayer`) to disable the normalization.

**Comment by kylebarron** [comment] 2019-11-23 03:18
Regarding the 404 errors, those are occurring because those paths don't exist in the `mbtiles` file. If you download the example `mbtiles` file in the original post, and then run 
```
> pip install mbutil
> mb-util geo_test.mbtiles tiles
> ls tiles/2/0
1.png 2.png
```
you see that 
```
DeckGl.js:40 GET http://localhost:3000/api/mbtiles/2/0/0.pbf 404 (Not Found)
```
is occurring because that doesn't exist in the file.

**Comment by kylebarron** [comment] 2019-11-23 04:04
Regarding the random lines, I can confirm that I'm also seeing them. Even when I use @Pessimistress' suggestion, and set `stroked: false`, I have these lines popping up:
![image](https://user-images.githubusercontent.com/15164633/69472717-ecdfb600-0d6a-11ea-89d3-d94758825026.png)

If I zoom out just a little, the lines disappear
![image](https://user-images.githubusercontent.com/15164633/69472721-0254e000-0d6b-11ea-981f-233f9b76810b.png)

Based on where the lines are, I suspect this is something with the vector tile parsing. You can see in @Martizs' [screenshot](https://drive.google.com/file/d/1ttx3jxGAUTxCTDK-QpqDIVuy2PL_Xz8L/view?usp=sharing) that the lines are happening at the equator and prime meridian. I haven't checked yet but I'm guessing my lines are at tile borders too.

**To reproduce:** 

My tiles are hosted on S3 without an API key, so it should be easy to test. Here's my `TileLayer`, and then I just pass that to Deck.gl's `layers` prop.

```js
import { TileLayer } from '@deck.gl/geo-layers';
import { VectorTile } from '@mapbox/vector-tile';
import Protobuf from 'pbf';

const tileLayer = new TileLayer({
  stroked: false,
  pickable: true,

  getLineColor: f => f.geometry.type === 'LineString' ? [0, 128, 239] : [0, 0, 0, 0],

  // getLineColor: [0, 0, 0],
  getFillColor: [77, 77, 77],

  opacity: 0.2,

  maxZoom: 11,

  getLineWidth: () => {
    return 1;
  },
  lineWidthMinPixels: 1,

  getTileData: ({ x, y, z }) => {
    const mapSource = `https://tiles.nst.guide/nationalpark/${z}/${x}/${y}.pbf`;
    return fetch(mapSource)
      .then(response => {
        if (response.status === 200) {
          return response.arrayBuffer();
        }
        return null;
      })
      .then(buffer => {
        if (buffer) {
          const tile = new VectorTile(new Protobuf(buffer));
          const features = [];
          for (const layerName in tile.layers) {
            const vectorTileLayer = tile.layers[layerName];
            for (let i = 0; i < vectorTileLayer.length; i += 1) {
              const vectorTileFeature = vectorTileLayer.feature(i);
              const feature = vectorTileFeature.toGeoJSON(x, y, z);
              features.push(feature);
            }
          }
          return features;
        }
        return [];
      });
  },

  onClick: ({ object }) => {
    console.log('hover object.properties', object && object.properties);
  },
});

export default tileLayer;
```

**Comment by kylebarron** [comment] 2019-11-23 04:32
When you zoom in far enough with a large enough polygon, you can see a grid form. I assume that means there's an off-by-one error somewhere in the loop, but I haven't found where yet.
![image](https://user-images.githubusercontent.com/15164633/69473057-37fbc800-0d6f-11ea-9dda-2c366a661d1a.png)

**Comment by kylebarron** [comment] 2019-11-23 06:55
It turns out this is caused by a bug in @mapbox/vector-tile.

**Comment by kylebarron** [comment] 2019-11-23 07:35
Also @Pessimistress once the bug in @mapbox/vector-tile is fixed, the example can become much easier using @mapbox/vt2geojson.

Something like
```
vt2geojson({
    uri: 'http://api.example.com/9/150/194.mvt'
}, function (err, result) {
    if (err) throw err;
    return result;
});
```

Instead of

```
return fetch(mapSource)
  .then(response => {
    if (response.status === 200) {
      return response.arrayBuffer();
    }
    return null;
  })
  .then(buffer => {
    if (buffer) {
      const tile = new VectorTile(new Protobuf(buffer));
      const features = [];
      for (const layerName in tile.layers) {
        const vectorTileLayer = tile.layers[layerName];
        for (let i = 0; i < vectorTileLayer.length; i += 1) {
          const vectorTileFeature = vectorTileLayer.feature(i);
          const feature = vectorTileFeature.toGeoJSON(x, y, z);
          features.push(feature);
        }
      }
      return features;
    }
    return [];
  });
```

**Comment by kylebarron** [comment] 2019-11-23 20:47
The fix for this needs to be in https://github.com/mapbox/vector-tile-js, but the last commit there was almost two years ago, so I'm not holding my breath. 

I did find a workaround, however. The problem is that the GeoJSONs returned by `@mapbox/vector-tile` are outside the bounds of the given `x,y,z` tile. A simple fix for this is to get the bounds of the tile and then clip the GeoJSON using Turf.js.

New dependencies `@mapbox/sphericalmercator` and `@turf/bbox-clip`; code:

```js
import { TileLayer } from '@deck.gl/geo-layers';
import { VectorTile } from '@mapbox/vector-tile';
import Protobuf from 'pbf';
import SphericalMercator from '@mapbox/sphericalmercator';
import bboxClip from '@turf/bbox-clip';

const sphericalMercator = new SphericalMercator();

...

  getTileData: ({ x, y, z }) => {
    const mapSource = `https://tiles.nst.guide/nationalpark/${z}/${x}/${y}.pbf`;
    const xyzBox = sphericalMercator.bbox(x, y, z);
    return fetch(mapSource)
      .then(response => {
        if (response.status === 200) {
          return response.arrayBuffer();
        }
        return null;
      })
      .then(buffer => {
        if (buffer) {
          const tile = new VectorTile(new Protobuf(buffer));
          const features = [];
          for (const layerName in tile.layers) {
            const vectorTileLayer = tile.layers[layerName];
            for (let i = 0; i < vectorTileLayer.length; i += 1) {
              const vectorTileFeature = vectorTileLayer.feature(i);
              const feature = vectorTileFeature.toGeoJSON(x, y, z);
              // clip to x, y, z box
              const clippedFeature = bboxClip(feature, xyzBox);
              features.push(clippedFeature);
            }
          }
          return features;
        }
        return [];
      });
  },
```

No polygon overlaps! (Although there is some flickering when panning the map.)
![image](https://user-images.githubusercontent.com/15164633/69485033-940a2f00-0df7-11ea-98a1-84af07b84bbc.png)

**Comment by kylebarron** [comment] 2019-11-26 20:41
Given the response in https://github.com/mapbox/vector-tile-js/issues/68, this is intended behavior, and not a bug there. You should either create vector tiles with no buffer or clip the tiles to the bounding box, as I mentioned in the previous comment.

**Comment by drewgoodwin2** [comment] 2019-11-26 21:38
Is there a way to combine the clipped features in either `getTileData` or `renderSubLayers` so that you have the true geometry in your data property? I think this is how mapbox gl js is rendering vector tiles, since the features that overlap tile borders are duplicated instead of clipped (https://github.com/mapbox/mapbox-gl-js/issues/3751)

**Comment by kylebarron** [comment] 2019-11-26 21:58
I think that would be hard because actual geometries can span many tiles. And the client wouldn't know how many tiles it needs to fetch. And I'm guessing that right now in deck.gl, every tile fetch is independent?

**Comment by kylebarron** [comment] 2019-12-25 07:41
I found that the flickering when panning was too much. I did however find that a good workaround is to specify the vector layer as a `react-map-gl` source and layer:

This is way easier because you're not loading and parsing the vector tiles yourself; you're presumably passing the layer to the Mapbox instance within react-map-gl. It also means you can use the full range of Mapbox styling available documented in their style specification.

```jsx
import DeckGL from "@deck.gl/react";
import {
  _MapContext as MapContext,
  StaticMap,
  NavigationControl,
  Marker,
  Source,
  Layer,
} from "react-map-gl";

class Map extends React.Component {
  render() {
    return (
      <DeckGL
        initialViewState={initialViewState}
        controller={true}
        // layers={layers}
        ContextProvider={MapContext.Provider}
      >
        <StaticMap mapStyle={mapStyle} touchRotate={true}>
          <Source
            id="nationalpark"
            type="vector"
            url="https://tiles.nst.guide/nationalpark/tile.json"
          >
            <Layer
              id="nationalpark_fill"
              type="fill"
              source-layer="nationalpark"
              paint={{
                'fill-opacity': 1,
                'fill-color': '#d8e8c8',
              }}
            />
          </Source>
        </StaticMap>
      </DeckGL>
    );
  }
}
```
![image](https://user-images.githubusercontent.com/15164633/71437456-1adc5100-26af-11ea-8da4-e9bfcf99c61f.png)

**Comment by Pessimistress** [comment] 2019-12-28 07:45
I do not believe mapbox merges feature cross multiple tiles. Their features are slightly larger than the tile itself, and get clipped off at the tile boundary.

`TileLayer` can potentially offer a "mask" option that does similar clipping.

Ultimately, deck.gl's `TileLayer` does not aim to replicate the features of mapbox-gl. It offers a generalized implementation of the data tiling and load-on-demand idea, without dictating what format you define the tiles in. It is never going to be as optimized and sophisticated as Mapbox itself in rendering their vector tile format.

**Comment by kylebarron** [comment] 2019-12-28 18:55
It seems like https://github.com/uber/deck.gl/pull/3935 could be helpful for this use case.

Alternatively, is there an ideal way to pass some layers directly to `react-map-gl` and still be able to be clicked? Obviously Mapbox renders the vector tiles well, so it seems like this option would provide good rendering. In my [comment from 3 days ago](https://github.com/uber/deck.gl/issues/3824#issuecomment-568858486), I was never able to get `onClick` to work with a `react-map-gl` layer, and also everything crashed on every hot reload, saying that my `key`s needed to be unique.

**Comment by Pessimistress** [comment] 2020-01-03 20:50
@kylebarron react-map-gl's [interactiveLayerIds](https://uber.github.io/react-map-gl/#/Documentation/api-reference/interactive-map?section=interaction-options) might be what you are looking for.

The React `key` message is just a warning, not the reason for the crash. Though we should fix that.

Can you open an issue in react-map-gl about the hot reload?

**Comment by kylebarron** [comment] 2020-01-04 00:35
> Alternatively, is there an ideal way to pass some layers directly to `react-map-gl` and still be able to be clicked? Obviously Mapbox renders the vector tiles well, so it seems like this option would provide good rendering.

I was able to figure this out. See https://github.com/uber/deck.gl/issues/4093 for an example of passing `onClick` events to React Map GL's `queryRenderedFeatures`. This lets you render a vector source as a child of Deck.GL and still use `onClick` events correctly.

**Comment by kylebarron** [comment] 2020-06-24 00:25
As of 8.1 there's a purpose-built MVTLayer which performs clipping where necessary, which should fix this issue.

**Closed by kylebarron** 2020-06-24 00:25 UTC

**Comment by mz8i** [comment] 2022-10-25 20:46
For anyone who might come here with a similar problem on deck.gl versions >=8.1 (like I did): for this to work, MVTLayer passes `extensions: [new ClipExtension()]` as one of the props to the sub-layers rendered in `renderSubLayers`. In my case, the problem was that I was rendering custom sublayers, and manually setting a value for the `extensions` property, which would then overwrite the `ClipExtension`. Merging the two `extensions` arrays solved the issue for me. 

In general, if you're still seeing artifacts like the above when using `MVTLayer`, make sure you are not overwriting any of the crucial props that `MVTLayer` sets for its sub-layers.
