### ISSUE TITLE
Tiles boundaries cause flickering effect

### ISSUE THREAD

**Issue by ramiissat** [visgl/deck.gl#3617] opened 2019-09-17 14:03 UTC
Applying the steps described in [the documentation](https://github.com/uber/deck.gl/blob/master/docs/layers/tile-layer.md) to add simple polygone TileLayer with mapbox-gl, I've got the following result, where neighboring tiles seem to intersect with each other, and therefore a flickering effect occurs because of the overlapped polygons. 

Is there a recommended approach to overcome this problem?
![WeChat Image_20190917214515](https://user-images.githubusercontent.com/3352501/65048502-d1d17e00-d996-11e9-8375-4110fce50398.png)

**Comment by kylebarron** [comment] 2019-11-23 05:09
I think this is the same issue as #3824

**Comment by kylebarron** [comment] 2020-06-24 00:26
Closing as this is a duplicate of #3824, and should be fixed with the MVTLayer as of 8.1

**Closed by kylebarron** 2020-06-24 00:26 UTC
Labels: question
