### ISSUE TITLE
instancePickingColors is allocated for non-pickable PathLayer

### ISSUE THREAD

**Issue by andreasg123** [visgl/deck.gl#6211] opened 2021-09-19 20:30 UTC
#### Description

`PathLayer` always allocates `instancePickingColors` even though it isn't pickable or has a highlighted element. As this `PathLayer` has 4 million polygons with 33 vertices each, this allocates a very large typed array, especially with the default over-allocation strategy (`numInstances`: 132 million, `size`: 3, `overAlloc`: 2: `Uint8ClampedArray` of size 792 million). That is 75% of the position data.

#### Expected Behavior
`instancePickingColors` should be allocated the first time they are needed.

#### Repro Steps
Create a `PathLayer` with binary attributes.

#### Environment
 - Framework Version: 8.4.17
 - Browser Version: Chrome 93.0.4577.82
 - OS: Mac OS X 10.15.17

**Comment by ibgreen** [comment] 2021-09-21 13:57
Another possibly simple improvement:
- It may make sense to just cap the overallocation factor for very large arrays. It could be done silently or exposed as a parameter (maxOverallocationSize). This might give you a 2x reduction even when enabling picking.

Also 
- I believe deck maintains two copies of the pickingBuffer arrays, one on CPU and one on GPU. Dropping the CPU array would give another 2x reduction in overall memory pressure.

Noe I believe PathLayer is special in that it uses multiple instances per path, so it needs a custom instancePickingColors array.

But most instanced layers have a simple row <-> instance correspondence, meaning that their instancePickingColors arrays are identical:
- For WebGL1, we could share a single `instancePickingColors` sized for the largest layer
- For WebGL2, we may not need the `instancePickingColors` attribute at all, as should have access to a `gl_InstanceId` variable in the shader, so we might be able auto generate the picking colors from that.

Finally, my understanding is that as of today, WebGL 2 has finally become available on iOS 15 meaning that may be able to start relying more heavily on WebGL2-only features

**Comment by Pessimistress** [comment] 2021-09-21 18:59
@andreasg123 I cannot reproduce this issue, see Codepen here: https://codepen.io/Pessimistress/pen/qBjKPva

![Screen Shot 2021-09-21 at 11 55 29 AM](https://user-images.githubusercontent.com/2059298/134231038-ba94a758-96be-4c06-83af-41ac1931290d.png)

@ibgreen I'm going to close this issue if it is not a bug. We need a separate issue to track picking color improvements in the v9 milestone.

> I believe deck maintains two copies of the pickingBuffer arrays, one on CPU and one on GPU. Dropping the CPU array would give another 2x reduction in overall memory pressure.

This is only true for PathLayer and SolidPolygonLayer. Regular instanced layers share the same CPU buffer.

**Comment by andreasg123** [comment] 2021-09-21 21:28
@Pessimistress, let me try to create a small example that can reproduce this. In general, would it make sense to create `instancePickingColors` greater than 16 million? It was my understanding that that was the limit, unless multiple points would get assigned the same picking color.

**Comment by andreasg123** [comment] 2021-09-21 21:35
@Pessimistress, you didn't open the `state` tab where `allocatedValue` is `Uint8ClampedArray(48)`.
![Screen Shot 2021-09-21 at 2 31 48 PM](https://user-images.githubusercontent.com/15636985/134250796-00810b43-020c-4243-bae3-c75e6a002e59.png)

**Comment by Pessimistress** [comment] 2021-09-24 21:53
Fixed in 8.5.10

**Closed by Pessimistress** 2021-09-24 21:53 UTC
Labels: bug
