### ISSUE TITLE
Cannot load library in ParcelJS production builds

### ISSUE THREAD

**Issue by andytango** [visgl/deck.gl#6351] opened 2021-11-02 20:24 UTC
#### Description
The parcel development server works fine, however the production builds fail. This could be due to Parcel's inlining or tree shaking behavior. 

The specific error appears to be caused by the `global` object in `probe.gl` being exported as `undefined`, causing a crash in the entrypoint file of `luma.gl`.  

My understanding of Parcel and the build systems of these libraries isn't sufficient to find a fix or workaround.

I acknowledge this may not technically be the best place to raise this issue compared to the other two projects. My thinking however is that `deck.gl` is more likely to be directly used by users of ParcelJS (React application developers).

Using:
- ParcelJS
- React
- Affects both JS and Typescript builds

#### Expected Behavior
When running a production build with ParcelJS, the created bundle loads in the browser without fatal errors.

#### Repro Steps

See [test repo](https://github.com/andytango/parcel-deckgl-test)

1. Set up simple ParcelJS application with React
2. Use example site from deck.gl site
3. Run parcel production build
4. Run a local web server on this bundle
5. Observe error in the console.

#### Environment
 - Framework Version: [e.g. deck.gl 8.6.1 / pydeck 0.5.0]
 - Browser Version: [e.g. Chrome 95]
 - OS: Mac OS X 11.6, also with Windows 10 (built on WSL Debian Buster)

#### Logs
`Uncaught TypeError: Cannot read properties of undefined (reading 'luma')`

**Comment by Pessimistress** [comment] 2021-11-04 19:07
I poked around the production bundle and it appears that Parcel replaced the named export `gloabal` with `$parcel$global` here:

https://github.com/uber-web/probe.gl/blob/3.0-release/modules/core/src/env/globals.js#L20

I don't know if this is a configurable thing, if not it feels like a bug in ParcelJS.

**Comment by ibgreen** [comment] 2021-11-04 19:12
Just a side note, I am generally moving other vis.gl frameworks over to directly use [`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) instead of importing our `global` and expect to eventually be able to phase out the `global` export.

**Comment by Pessimistress** [comment] 2021-11-04 19:17
@ibgreen I do not think that is the issue here. I can see that `global` is correctly populated (to `window`) but gets exported as `$parcel$global` instead.

**Comment by Pessimistress** [comment] 2021-11-04 19:27
@andytango If you need to report this to ParcelJS here is a minimal repro:

Replace your app.tsx with

```js
import {global} from "probe.gl/env";
console.log(global);
```

In the dev build (`yarn start`) it prints `Window`.
In the prod build (`yarn build`) it prints `undefined`.

To see the name replacement issue, open the bundle (not the source map) in the debugger, and set a break point here:

![image](https://user-images.githubusercontent.com/2059298/140405942-365edc16-9ef7-4435-a9a2-bc6e870b335b.png)

**Comment by Pessimistress** [comment] 2021-11-04 19:51
You can also reproduce this without any dependency:

```js
/// env.js
export const global = window;
```

```js
/// env-es5.js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.global = window;
```

```js
/// app.tsx
import * as env from "./env";
import * as env2 from './env-es5';

console.log(env);
// --> {global: (...)}{
console.log(env2);
// --> {$parcel$global: (...)}
```

**Comment by jpoehnelt** [comment] 2022-03-25 20:50
I believe the same issue is in `probe.gl/env.js`, which is used by the latest `@luma.gl/gltools` (fixed in alpha). This is an issue for me since I'm trying to use skypack (not possible to force versions of deps) which has a similar problem with `global`.

**Comment by ibgreen** [comment] 2022-03-25 23:20
Are you using latest versions? Maybe check your lock file? 

This issue bubbled up about 3 months ago and we split out a proper new module `@probe.gl/env` that uses `globalThis` which fixed the problems at that time. We effectively deprecated the hacky `probe.gl/env.js` import.

**Comment by Pessimistress** [comment] 2022-05-11 16:24
This is resolved with luma.gl v8.5.11. You may need to remove your lock file and reinstall dependencies.

**Closed by Pessimistress** 2022-05-11 16:24 UTC
Labels: bug
