### ISSUE TITLE
[Bug]: Icon is not showing

### ISSUE THREAD

**Issue by AmirSarrafzadeh** [visgl/deck.gl#8758] opened 2024-04-05 08:37 UTC
### Description

I hope you are doing well,
I have used this icon in my project, but I could not see the icon in my map.
https://icons.iconarchive.com/icons/custom-icon-design/flatastic-9/256/Accept-icon.png

I used the icon for the documentation, it shows correctly, but I did not figure out what is the problem of Pydeck with this icon.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I expected to see the green ison on the map.

### Steps to Reproduce

Please check Streamlit repository in my github, the 04_routing folder

### Environment

- Framework version:
- Browser:
- OS:

**Comment by jeafreezy** [comment] 2024-04-05 09:42
Hi,

Can you try to convert the icon to Base64 encoding using any online tool (e.g https://base64.guru/converter/encode/image/png), and pass the string.

This was what worked for me in my recent experience with icons, I hope it helps!

**Comment by Pessimistress** [comment] 2024-04-05 11:48
@AmirSarrafzadeh Request to the URL is blocked by [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) i.e. the server at icons.iconarchive.com does not want you to use it. You can embed it inline as @jeafreezy suggests, or copy it to your own repo and use the GitHub raw URL.

Closing this as it is not a bug. If you have further questions, please use Discussions.

**Closed by Pessimistress** 2024-04-05 11:48 UTC
