### ISSUE TITLE
Trying to integrate deck.gl with Vite fails when building (promisify error)

### ISSUE THREAD

**Issue by fdb** [visgl/deck.gl#5551] opened 2021-03-01 16:08 UTC
#### Description

When trying to use deck.gl with [Vite](http://vitejs.dev/), running `npm run build` fails with an error about promisify. I've [crossposted this bug](https://github.com/vitejs/vite/issues/2320) in the Vite repo since I'm not sure if it's a Vite issue or a Deck.gl issue.

#### Expected Behavior

I expect `npm run build` to generate a clean output build. Running the dev server (`npm run dev`) works well.

#### Repro Steps

Here's a demonstration repo: <https://github.com/fdb/vite-bug-deck-gl>.
I've also made a demonstration repo with webpack, which does not give an error: <https://github.com/fdb/webpack-deck-gl>

1. Make a new Vite project with `npm init @vitejs/app` and choose Vanilla. `cd` into the folder and install dependencies.
2. Install `deck.gl` with `npm install @deck.gl/core @deck.gl/layers`
3. Replace the code in `main.js` with the basic ["hello world" example](https://deck.gl/docs/get-started/using-standalone)
4. The dev server (`npm run dev`) works well. 
5. Try to build it with `npm run build`

This gives the following error:

```bash
vite v2.0.4 building for production...
✓ 515 modules transformed.
'promisify' is not exported by __vite-browser-external, imported by node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js
file: /Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js:2:9
1: import fs from 'fs';
2: import { promisify } from 'util';
            ^
3: import { toBuffer } from '@loaders.gl/loader-utils';
4: export function writeFile(filePath, arrayBufferOrString, options) {
```

(The full log is below)

#### Environment
 - Framework Version: deck.gl 8.4.9,
 - Browser Version: Not relevant (build issue)
 - OS: macOS Big Sur 11.2.2

#### Logs

```bash
vite v2.0.4 building for production...
✓ 515 modules transformed.
'promisify' is not exported by __vite-browser-external, imported by node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js
file: /Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js:2:9
1: import fs from 'fs';
2: import { promisify } from 'util';
            ^
3: import { toBuffer } from '@loaders.gl/loader-utils';
4: export function writeFile(filePath, arrayBufferOrString, options) {
error during build:
Error: 'promisify' is not exported by __vite-browser-external, imported by node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js
    at error (/Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/rollup/dist/shared/rollup.js:5279:30)
    at Module.error (/Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/rollup/dist/shared/rollup.js:9996:16)
    at Module.traceVariable (/Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/rollup/dist/shared/rollup.js:10389:29)
    at ModuleScope.findVariable (/Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/rollup/dist/shared/rollup.js:8847:39)
    at FunctionScope.findVariable (/Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/rollup/dist/shared/rollup.js:2641:38)
    at ChildScope.findVariable (/Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/rollup/dist/shared/rollup.js:2641:38)
    at Identifier.bind (/Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/rollup/dist/shared/rollup.js:4017:40)
    at CallExpression.bind (/Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/rollup/dist/shared/rollup.js:2728:23)
    at CallExpression.bind (/Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/rollup/dist/shared/rollup.js:6730:15)
    at CallExpression.bind (/Users/fdb/Desktop/vite-test-deck-gl/vite-test-deck-gl/node_modules/rollup/dist/shared/rollup.js:2728:23)
```

**Comment by Pessimistress** [comment] 2021-03-01 17:02
As the log suggests, the error happens when importing `node_modules/@loaders.gl/core/dist/esm/node/write-file.node.js `. Your bundler is trying to import a file that is marked not for the browser: https://github.com/visgl/loaders.gl/blob/2.3-release/modules/core/package.json#L29

Closing this since it's not related to deck.gl. If you have suggestions on how loaders.gl should distribute its modules please open an issue in the loaders.gl repo.

**Closed** 2021-03-01 17:02 UTC

**Comment by mdugue** [comment] 2021-07-07 07:24
@fdb did you find any solution on running **deck.gl** with **vite** by now? 

I just stumbled upon a similar problem when trying to use the deck.gl / vite combination. The error seems to be a bit different though: 

> Super expression must either be null or a function

which is caused by  the buffer.js file from **luma.gl**. Any hints / working examples would be great and really helpful!

**Comment by fdb** [comment] 2021-07-07 08:23
@mdugue no I switched to create-react-app/webpack, unfortunately.

**Comment by njaldea** [comment] 2021-07-23 05:13
I am able to use deck.gl with sveltekit. The issue is only encountered when loader.gl is used.
try `npm install --legacy-peer-deps` or using yarn instead.

that fixed svelte-kit build. next problem is, svelte-kit dev is broken due to some circular dependency issue.

**Comment by yongjun21** [comment] 2021-12-06 16:18
> @fdb did you find any solution on running **deck.gl** with **vite** by now?
> 
> I just stumbled upon a similar problem when trying to use the deck.gl / vite combination. The error seems to be a bit different though:
> 
> > Super expression must either be null or a function
> 
> which is caused by the buffer.js file from **luma.gl**. Any hints / working examples would be great and really helpful!

Try
```
define: {
    Buffer: 'Error',
}
```
