### ISSUE TITLE
Layers above a Deck GeoJsonLayer are not rendered visible above Feature

### ISSUE THREAD

**Issue by JesalR** [visgl/deck.gl#6504] opened 2021-12-14 14:48 UTC
#### Description
When rendering a Deck GeoJSON layer with a feature, and rendering a Deck Icon layer above it on a mapbox map via react-map-gl, the icons are not visible in the area above the GeoJSON feature.  Icons beneath the feature are rendered correctly and are occluded by the feature opacity.

- React
- Vendor integration: MapboxLayer and react-map-gl

#### Expected Behavior
Expect to see icons above the geojson feature

#### Repro Steps
- use `MapboxLayer` to create layers
- add layer to map using `.addLayer`, following https://deck.gl/docs/api-reference/mapbox/mapbox-layer#make-a-layer-from-scratch
- Position GeoJSON below icons

- Example
https://codesandbox.io/s/deck-geojson-order-wf84w?file=/src/App.js
- flip comments on `map.moveLayer` to change order

- Occluded icons that should be above feature
![image](https://user-images.githubusercontent.com/884436/146020827-b1b0440f-463d-47d2-a34d-a8ee696d0aab.png)

- Icons rendered correctly beneath
![image](https://user-images.githubusercontent.com/884436/146020929-dad307b8-30f5-444a-8fae-0bf59aecceb0.png)

#### Environment
 - Framework Version: deck.gl 8.6.5, react-map-gl 6.1.18 (all latest)
 - Browser Version: Chrome 96.0.4664.55
 - OS: macOS 11.6

#### Logs
NA

**Comment by AdriSolid** [comment] 2021-12-15 12:06
Try setting `depthTest` as false in `parameters` prop.

[Docs](https://deck.gl/docs/developer-guide/tips-and-tricks#z-fighting-and-depth-testing)

**Comment by JesalR** [comment] 2021-12-15 12:44
> Try setting `depthTest` as false in `parameters` prop.
> 
> [Docs](https://deck.gl/docs/developer-guide/tips-and-tricks#z-fighting-and-depth-testing)

Not really certain where that goes in a layer using MapboxLayer. I tried adding the parameters group to that constructor in the codesandbox above and it didn't make a difference

**Comment by Pessimistress** [comment] 2021-12-15 22:13
You want to add the above parameters to the `icons` layer. I can see it working in your CodeSandbox:

**Comment by Pessimistress** [comment] 2021-12-16 10:13
Closing as a duplicate of #6284, please track progress in the other issue.

**Closed by Pessimistress** 2021-12-16 10:13 UTC
Labels: bug
