### ISSUE TITLE
[Bug] DeckGL crashes IOS devices (tested IOS v15.6 and v16) when zooming 

### ISSUE THREAD

**Issue by niko-dellic** [visgl/deck.gl#7430] opened 2022-11-18 20:13 UTC
### Description

I have encountered a bug where DeckGL crashes the entire page on IOS devices in any browser. If you have an iPhone, you should be able to reproduce the symptom [here](https://niko-dellic.github.io/mobile-ios-deckgl-issue/). You can see the repo [here](https://github.com/niko-dellic/mobile-ios-deckgl-issue/blob/main/index.html), but it is the basic [carto example](https://github.com/visgl/deck.gl/tree/master/examples/get-started/scripting/carto) from the DeckGL repo. I haven't had the opportunity to test it on an IPad.

In attempting to isolate the issue, Here's what I know:

1. Zooming in and out with your fingers causes the site to crash. The faster you do it, the faster it happens. It usually takes about 1-2 seconds.
2. If you add a button to trigger a view state change (even with flyToInterpolator), the site does not crash.
3. The site crashes on iPhones, tested on IOS v15.6 and 16.0.
4. It happens when using script tags and importing any version of Mapbox via script tags
5. It does **not** happen if you use Mapbox via the interleaving method, even if you import via script tags. [This](https://deck.gl/gallery/mapbox-layer) example works fine on IOS.
6. it does **not** happen if you host the code on [codepen](https://codepen.io/niko-dellic/full/poKRJNB), but live versions via Vercel and GitHub pages both experience the issue. 

Let me know if there is anything else I can provide to help. From pure anecdote, I have a feeling there might be a memory leak issue somehow connected to touch input, but I am not experienced enough to say it with confidence. 

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

![img_4518](https://user-images.githubusercontent.com/39039032/202792651-a7ce884a-51d6-49c7-bedc-5f7761200ae2.png)

### Steps to Reproduce

This issue does not happen when hosted via CodePen. I was using GitHub pages to test the issue. The code is available from the examples [here](https://github.com/visgl/deck.gl/tree/master/examples/get-started/scripting/carto).

### Environment

- Framework version: 8.8.0
- Browser: Tested with IOS Chrome and Safari
- OS: IOS 15.6, 16

### Logs

Unfortunately, there are no logs reported when the site crashes.

**Comment by Pessimistress** [comment] 2022-11-21 19:13
I am unable to reproduce this (iPhone SE 2020, iOS 15.7.1)

**Comment by Radik24** [comment] 2022-11-22 16:15
Hi,

I'm experiencing something similar on iPad Air M1 2022, but randomly... We do not use Mapbox. It just reloads page sometimes, but I was not able to reproduce it again...as I said it happens randomly it seems. I attached safari debugger to iPad, but there is no error in console...never...just reload 😄 

We also have mobile app where we use _typedArrayManagerProps => https://deck.gl/docs/developer-guide/tips-and-tricks#experimental-memory-usage-controls and app is not crashing. But to be fair mobile app is much simpler and supports less layers than web app currently.

Maybe you/we should use _typedArrayManagerProps in web app too.

If I find something I'll let you know.

**Comment by zakjan** [comment] 2022-11-22 17:36
Reproduced on iPhone 12 Mini, iOS 16.1.

I used to see similar crashes during pinch zoom with iOS 15 since the upgrade to WebGL 2 with Metal backend, but it got fixed for me with iOS 16. I even filled a WebKit bug report, but they couldn't reproduce it either. https://bugs.webkit.org/show_bug.cgi?id=235594

Are there any useful logs to collect to be able to investigate such crashes?

**Comment by kylebarron** [comment] 2022-11-22 17:46
just adding that I can reproduce on iPhone 13 Mini, iOS 16.1.1

**Comment by Radik24** [comment] 2022-11-22 19:21
ipad air m1, ipados 16.1.1
- safari - working
- chrome - working

iphone 13 mini, ios 16.1.1
- safari - crashing - no logs in browser console
- chrome - crashing - no logs in browser console

iphone 6s, ios 15.7
- safari - working
- chrome - working

**Comment by OlivierRiberi** [comment] 2023-06-21 21:08
I'm able to reproduce the same issue very consistently on the official demo: https://deck.gl/examples/google-3d-tiles

On iPhone 13 mini, iOS 16.5, Safari:
I can move around but when I try to rotate or zoom, first it will refresh the page automatically, then if I try again, it will crash completely.

**Comment by dschor-cubicsearch** [comment] 2023-11-22 03:07
Reproduced in my project. https://images.cubicsearch.com/meta/surveys/587.html

**Comment by kkornakiewicz** [comment] 2024-09-11 12:08
For anyone coming here from Google, I struggled with this problem with my personal project and issue seem to be resolved by setting flag: `useDevicePixels` to false.

https://deck.gl/docs/api-reference/core/deck

**Comment by ibgreen** [comment] 2024-09-13 11:20
Mobile crashes are very often caused by browser shutting down the tab when it exceeds a memory threshold. 
- Since mobile devices tend to have high DPI (2x or even 4x), the framebuffers (off screen textures) that deck needs to allocate to render at full resolution can become very big, so avoiding device pixels usually helps a lot, often with rather minor visual quality reduction (since the screens are small).
-Another note is that enabling picking also allocates off-screen buffers so consider whether picking is needed on your mobile device.
- If we don't have it already, it could be good to add a section in the deck.gl docs with some tips for mobile.

**Comment by ibgreen** [comment] 2024-09-13 11:21
Suggest we move this discussions, issues are for actionable issues.

**Closed by ibgreen** 2024-09-13 11:21 UTC
Labels: bug
