### ISSUE TITLE
map attribution icon (for small devices) not clickable 

### ISSUE THREAD

**Issue by jonenst** [visgl/deck.gl#5338] opened 2021-01-15 16:05 UTC
#### Description

On small devices, the map attribution is replaced with an icon but you can't click on it

#### Expected Behavior

small icon should be clickable

#### Repro Steps

compare (reduce the width of your window or use the dev responsive mode of the browser if you are on a normal PC)

http://visgl.github.io/react-map-gl/examples/layers
https://deck.gl/examples/geojson-layer-polygons/
![Capture d’écran de 2021-01-15 17-02-16](https://user-images.githubusercontent.com/89208/104749932-acec4700-5753-11eb-92b6-a6c30f877c95.png)

#### Environment
 - Framework Version: deck.gl 8.3.0
 - Browser Version: all
 - OS: all

**Comment by Pessimistress** [comment] 2021-01-15 16:29
Duplicate of #4165

**Closed** 2021-01-15 16:29 UTC
Labels: bug
