### ISSUE TITLE
Layers not working on production builds in Angular 12 [Bug]

### ISSUE THREAD

**Issue by gpinto8** [visgl/deck.gl#7937] opened 2023-06-07 07:56 UTC
### Description

I have a web component built in React 17 that returns a Deck.GL map.

When including this micro frontend in for example an Angular 11 solution, everything works locally, but when in production, it throws me an error of "o.resetOldProps is not a function" when initializing the layers:

![immagine](https://github.com/visgl/deck.gl/assets/59851308/6c4be077-8db6-4409-8183-f3268c9de6b2)
![immagine](https://github.com/visgl/deck.gl/assets/59851308/2dff73e0-0c14-4b19-bc6b-b9575269b3a9)

Of course, the map is not visible because of this error.

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

I expect it to work on production builds too.

### Steps to Reproduce

1. Create a Deck.gl Web Component Map production build using Webpack, here's ours:
![immagine](https://github.com/visgl/deck.gl/assets/59851308/8a76a8bc-a8f6-4830-aaf4-c376e46aa22b)
(we use the "react-web-component" library to create the web component)

2. Include it to another application in Angular 11, by creating a folder and pointing to it with the "angular.json" file. Create a component that points to your Web Component
![immagine](https://github.com/visgl/deck.gl/assets/59851308/cc6d8b1a-d1ab-425b-8fb6-c4b9c71a11b9)

3. Create a production build with "ng build --prod"

4. Use the following Python command: "python -m http.server 9000" on the build folder to create a local http server to test it, here you should see the error.

### Environment

- Framework version: deck.gl@8.9.14
- Browser: Firefox 113.0.2
- OS: Windows 10

**Comment by Pessimistress** [comment] 2023-06-07 15:20
Please provide a repo that reproduces your issue.

**Comment by gpinto8** [comment] 2023-06-08 15:10
Here's the repo: https://github.com/gpinto8/deckgl-build-problem/tree/main

Steps to reproduce it:

1. "npm i" and "npm run start" the "react-mfe" folder -> you should see a normal Deck.gl map (under the "web-component-test" tag)

2. Create a build with "npm run build" -> you should see something like this in the "dist" folder:
![immagine](https://github.com/visgl/deck.gl/assets/59851308/977ac2b0-04bd-49af-9309-d8bb44a13889)

3. Copy and paste the content of the "dist" folder on the "@mfe" folder of the "angular-host", you should see something like this:
![immagine](https://github.com/visgl/deck.gl/assets/59851308/34780096-4e4e-4804-8e6a-572f94cf2197)
(in that way, the angular will take the local build from "react-mfe" and use it (the config is in the "angular.json" file)

(TO EASE THINGS OUT, WE'VE ALREADY ADDED THE "react-mfe" BUILD TO THE "angular-host")

4. "npm i" and "npm run start" the "angular-host" folder -> you should see the same map as the "react-mfe" (still under the "web-component-test" tag)

Till here everything works as expected, but:

5. If we run a production build of the "angular-host" with "npm run build_PROD" -> a "dist" folder will be created
and then we go to that "dist/test" folder and run "python -m http.server 9000" (to create a local server) it will throw us this error:
![immagine](https://github.com/visgl/deck.gl/assets/59851308/a33059f0-cc77-4378-aff9-23f13f12b982)

**Comment by Pessimistress** [comment] 2023-06-08 16:23
If you replace the content of `scripts.<hash>.js` with that of `micro-frontend.js`, you can see the app works. Somewhere in your build config the file gets modified, likely due to aggressive optimization, which breaks the code.

This is not a problem within the deck.gl library, so I'm going to close the issue. I'm afraid I'm not familiar with the Angular ecosystem, and cannot offer any further advice.

**Closed by Pessimistress** 2023-06-08 16:23 UTC
Labels: bug
