### ISSUE TITLE
FillStyleExtension for PathLayer

### ISSUE THREAD

**Issue by TextTL** [visgl/deck.gl#5592] opened 2021-03-18 23:55 UTC
#### Target Use case
We have use cases to render different patterns for paths depending on conditions.  

#### Proposed feature
Currently path is rendered with color only. It would be great if PathLayer can utilize FillStyleExtension like PolygonLayer or ScatterplotLayer. 

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by kylebarron** [comment] 2021-03-19 00:03
Duplicate of https://github.com/visgl/deck.gl/discussions/5591

**Closed by kylebarron** 2021-03-19 00:03 UTC
Labels: feature
