### ISSUE TITLE
[Bug] Website Examples: Integrations ArcGis is not working on Android #7088

### ISSUE THREAD

**Issue by AnaDiaz85** [visgl/deck.gl#7097] opened 2022-06-27 12:03 UTC
### Description

I can’t visualize the integration of ArcGIS.

Android (Galaxy S22, Galaxy Tab S8 (ipad))
Chrome / Firefox / Samsung internet browser

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [X] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

It should work fine

### Steps to Reproduce

1. Go to https://pessimistress.github.io/deck.gl/examples/arcgis/

### Environment

Framework version: `8.8.0-beta`. `latest`
Browser:  Chrome / Firefox / Samsung internet browser
OS: Android

**Comment by Pessimistress** [comment] 2022-06-27 16:01
Duplicate of #6684

**Closed by Pessimistress** 2022-06-27 16:01 UTC
Labels: bug
