### ISSUE TITLE
Installing deck.gl doesn't install some of its direct dependencies

### ISSUE THREAD

**Issue by yudai-nkt** [visgl/deck.gl#6493] opened 2021-12-09 15:20 UTC
#### Description
Installing deck.gl doesn't install some of its direct dependencies (e.g., `@deck.gl/layers`).

#### Expected Behavior

Installing deck.gl should install all of its direct dependencies.

#### Repro Steps
```console
$ mkdir repro
$ cd repro
$ npm init -y
$ npm install deck.gl
$ node -e "console.log(fs.existsSync('node_modules/@deck.gl/layers'));"
false
```

#### Environment
 - Framework Version: deck.gl 8.6.4
 - Browser Version: N/A
 - OS: macOS Mojave

#### Logs
N/A

**Comment by yudai-nkt** [comment] 2021-12-09 15:22
I wonder how this could happen and might be missing something quite obvious...

**Comment by kylebarron** [comment] 2021-12-09 16:27
You might want to check that there's no parent directory with a `node_modules` folder. If I create a new temporary directory with no `node_modules` folder in a parent directory, and run `yarn add deck.gl`, then `node_modules/@deck.gl/layers` exists for me:

```
> tree -d node_modules/@deck.gl -L 1
node_modules/@deck.gl
├── aggregation-layers
├── carto
├── core
├── extensions
├── geo-layers
├── google-maps
├── json
├── layers
├── mapbox
├── mesh-layers
└── react

11 directories
```

```
> tree -d node_modules/@deck.gl/layers
node_modules/@deck.gl/layers
├── dist
│   ├── es5
│   │   ├── arc-layer
│   │   ├── bitmap-layer
│   │   ├── column-layer
│   │   ├── geojson-layer
│   │   ├── icon-layer
│   │   ├── line-layer
│   │   ├── path-layer
│   │   ├── point-cloud-layer
│   │   ├── polygon-layer
│   │   ├── scatterplot-layer
│   │   ├── solid-polygon-layer
│   │   └── text-layer
│   │       ├── multi-icon-layer
│   │       └── text-background-layer
│   └── esm
│       ├── arc-layer
│       ├── bitmap-layer
│       ├── column-layer
│       ├── geojson-layer
│       ├── icon-layer
│       ├── line-layer
│       ├── path-layer
│       ├── point-cloud-layer
│       ├── polygon-layer
│       ├── scatterplot-layer
│       ├── solid-polygon-layer
│       └── text-layer
│           ├── multi-icon-layer
│           └── text-background-layer
└── src
    ├── arc-layer
    ├── bitmap-layer
    ├── column-layer
    ├── geojson-layer
    ├── icon-layer
    ├── line-layer
    ├── path-layer
    ├── point-cloud-layer
    ├── polygon-layer
    ├── scatterplot-layer
    ├── solid-polygon-layer
    └── text-layer
        ├── multi-icon-layer
        └── text-background-layer

46 directories
```

**Comment by Pessimistress** [comment] 2021-12-09 16:58
`@deck.gl/layers` is listed as a dependency of `deck.gl`: https://unpkg.com/browse/deck.gl@8.6.4/package.json

Closing as this is not a bug in the library. Please use Discussions if you need help using npm.

**Closed** 2021-12-09 16:59 UTC

**Comment by yudai-nkt** [comment] 2021-12-09 22:28
@kylebarron Thank you for your suggestion. I checked, but there were no such directories. For example,

```console
$ mkdir /tmp/repro
$ cd /tmp/repro
$ ls ../node_modules
ls: cannot access '/tmp/node_modules': No such file or directory
$ npm init -y
$ npm install deck.gl
$ tree -d node_modules/@deck.gl -L 1
node_modules/@deck.gl
├── core
├── extensions
├── google-maps
├── json
├── mapbox
├── mesh-layers
└── react

7 directories
```
