### ISSUE TITLE
Random CI failure in master

### ISSUE THREAD

**Issue by alasarr** [visgl/deck.gl#5724] opened 2021-05-05 06:23 UTC
#### Description

After merge MVT triangulation for binary data it looks the test are failing:

https://github.com/visgl/deck.gl/runs/2501602495#step:5:6607

#### Expected Behavior
CI should pass

**Comment by alasarr** [comment] 2021-05-05 06:24
@Pessimistress reported me that MVT render tests are failing randomly, would be great @felixpalmer if you could take a look

**Comment by felixpalmer** [comment] 2021-05-05 09:00
I think this is related to what @Pessimistress reported, I re-ran the tests and they came through fine: https://github.com/visgl/deck.gl/runs/2507689263. I'm looking into what is the cause though

**Comment by felixpalmer** [comment] 2021-05-06 10:38
I've done some investigation and cannot pin down a cause. For reference here is a [failing run](https://github.com/visgl/deck.gl/runs/2492839975) and a [successful run](https://github.com/visgl/deck.gl/runs/2507689263). I've compared the raw logs using a diff viewer and can't find any clue as to why it is failing.

I've run the tests locally and the issue is not reproduced. Also re-running the tests on the CI system results in success.

It is true that I submitted a [PR](https://github.com/visgl/deck.gl/pull/5712) that touches the MVT layer, but we should note that this was pulling in a version of loaders.gl (3.0.0-alpha.6) on the CI system that didn't have the corresponding changes and thus should be a no-op as far as the CI is concerned.

Thus my conclusion here is that this is a spurious error, and I'm not inclined to investigate further. @Pessimistress if you have some useful background or ideas I'm all ears but right now I feel I've reached a point where it is too time-consuming to continue.

**Comment by ibgreen** [comment] 2021-05-06 23:46
@felixpalmer It is a render test that fails. The MVTLayer is rendered and compared against a "golden image" but the matching pixels are only 22%. 

Since the render delta is so big, and sporadic, it makes me think that it could be a timing issue - sometimes the tiles are loaded, sometimes not.

I though we had synchronization in place but maybe there is some issue with the MVT tile layer. We should probably look into that. 

The surprising thing is that your changes should make things load faster, so if there is indeed a sync issue it stands to reason that we should see less problems, not more.

Not sure if this gives you any actionable leads.

If the CI failure is very rare we might be able to land this. @Pessimistress will have to make the call.

**Comment by Pessimistress** [comment] 2021-05-06 23:48
The failure is not caused by this particular PR. It started showing up about a week ago.

**Comment by Pessimistress** [comment] 2021-05-24 02:06
Seems to be resolved by #5780

**Closed by Pessimistress** 2021-05-24 02:06 UTC
Labels: bug
