### ISSUE TITLE
[Bug] macOS sonoma Render exception

### ISSUE THREAD

**Issue by FEJackFly** [visgl/deck.gl#8127] opened 2023-09-21 10:04 UTC
### Description

<img width="1672" alt="image" src="https://github.com/visgl/deck.gl/assets/24688308/9c497e23-3957-4bbc-afe8-6679f76fac4b">
<img width="832" alt="image" src="https://github.com/visgl/deck.gl/assets/24688308/35838972-2082-4946-ace3-13c477c464db">

macOS sonoma 14.0 Render exception

macOS ventura Render smoothly without jagging

### Flavors

- [ ] Script tag
- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

macOS sonoma 14.0  

https://codesandbox.io/s/hungry-joliot-tmq3wl?file=/src/App.js

### Environment

- Framework version: "deck.gl": "^8.9.29"
- Browser: chrome 117.0.5938.88
- OS: macOS sonoma 14.0

**Comment by craigloftus** [comment] 2023-09-29 14:59
We were seeing a similar issue, and have been able to reproduce in both Chrome and Safari. Edge is unaffected.

The issue seems to be addressed in Chrome Beta (also seems to address your issue in the sandbox).

The grid (rasters) and the yellow polygons (vectors) should be uniform squares, but are stretched and compressed horizontally.

![Screenshot 2023-09-29 at 11 49 31](https://github.com/visgl/deck.gl/assets/88151/66f9aefe-5641-4f6c-9201-2ca88a834442)

We think the issue is with the Angle WebGL renderer but haven't been able to identify the associated issue upstream.

**Comment by craigloftus** [comment] 2023-10-25 20:14
To follow up on this... it is still a problem even with 118. As mentioned before the issue is with the WebGL renderer, specifically the ANGLE backend. With Sonoma it looks like this was changed to default to Metal for Chrome, rather than OpenGL. However the Metal backend is still considered experimental.

There is a workaround, you can change the ANGLE backend via a flag in chrome: `chrome://flags/#use-angle` and change the setting to OpenGL.

**Comment by FEJackFly** [comment] 2023-11-02 07:10
MacOS:14.1 
Chrome:118
This issue has been resolved
<img width="357" alt="image" src="https://github.com/visgl/deck.gl/assets/24688308/8945d824-8707-4713-b39d-aff76103e8d9">

**Closed** 2023-11-02 07:10 UTC
Labels: bug
