### ISSUE TITLE
[Bug] react draggable layer throws `setProps` is not a function

### ISSUE THREAD

**Issue by jessekrubin** [visgl/deck.gl#6682] opened 2022-02-23 02:18 UTC
### Description

When I use a deckRef with react and deckgl in a 'draggable' layer (which totally works), and try to call `setProps`, I get the  error below (in the chrome and firefox console(s)); the error cannot be try/catch-ed and doing a try/catch on the `setProps` call makes the layer no-longer draggable. 

ASIDE FROM THE ERROR IN THE BROWSER CONSOLE EVERYTHNG WORKS FINE!?!?!?!?!?!?

Error:

```
App.js:50 Uncaught TypeError: deckRef.current.setProps is not a function
    at IconLayer.onDragStart (App.js:50:1)
    at Deck._onEvent (deck.js:817:1)
    at EventRegistrar._emit (event-registrar.js:121:1)
    at EventRegistrar.handleEvent (event-registrar.js:96:1)
    at Manager.emit (hammer.js:2519:1)
    at emit (hammer.js:1527:1)
    at PanRecognizer.emit (hammer.js:1532:1)
    at PanRecognizer.emit (hammer.js:1817:1)
    at PanRecognizer.tryEmit (hammer.js:1555:1)
    at PanRecognizer.recognize (hammer.js:1602:1)
```

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [X] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

I don't know what I expect to see, but my call to `setProps` cannot be 

### Steps to Reproduce

checkout my repro-repo: https://github.com/jessekrubin/deckgl-drag-setprops-typeerror

### Environment

- Framework version:
- Browser:
- OS: windows/linux(rhel/ubuntu)

**Comment by Pessimistress** [comment] 2022-02-23 04:27
DeckGL's ref does not have a setProps method, see https://deck.gl/docs/api-reference/react/deckgl#methods

Closing because this is not a bug in the library. Use Discussions if you need help with your application.

**Closed** 2022-02-23 04:28 UTC
Labels: bug

**Comment by jessekrubin** [comment] 2022-02-23 04:48
@Pessimistress How would you recommend working around this?

**Comment by jessekrubin** [comment] 2022-02-23 05:07
@Pessimistress My draggable icon layer works and I'm not sure how else to make it work beyond forking the react sub package. 

Imo I should at least be able to call setProps and silence the error.

Did you try my repro?!??

**Comment by Pessimistress** [comment] 2022-02-23 20:40
> I'm not sure how else to make it work

If you want free support, at least pay the respect to follow directions.

![Screen Shot 2022-02-23 at 12 37 40 PM](https://user-images.githubusercontent.com/2059298/155404301-6880e91c-300a-49c4-b358-29e17c73d4ee.png)
