### ISSUE TITLE
[Bug] LineLayer not rendering in expected direction with repeat mode on(wrapLongitude)

### ISSUE THREAD

**Issue by Anand2489** [visgl/deck.gl#6950] opened 2022-05-25 09:23 UTC
### Description

LineLayer is taking longer route to render with repeat mode on(wrapLongitude)

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Ideally LineLayer should render via the shorter route. Any configuration to enable it ?

### Steps to Reproduce

<img width="1469" alt="Screenshot 2022-05-25 at 2 16 34 PM" src="https://user-images.githubusercontent.com/5299907/170223552-f7d63b1d-d14a-47f8-9a7b-90bac786fb5c.png">

### Environment

- Framework version: 8.7.3
- Browser: Brave
- OS: MacOS

**Comment by Pessimistress** [comment] 2022-05-25 11:25
Please provide a codepen that reproduces your issue.

**Comment by Anand2489** [comment] 2022-05-25 18:07
@Pessimistress https://codepen.io/andycool/pen/ExQbbeG?editors=001

**Comment by Anand2489** [comment] 2022-05-25 21:24
@Pessimistress After setting `wrapLongitude` to `true`, I'm getting following result (updated the codepen). As per the DeckGL [documentation](https://deck.gl/docs/api-reference/core/layer#wraplongitude), it says that the line is split into 2 across 180th meridian which I think is a recommendation from [GeoJson](https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.9). 

<img width="1212" alt="Screenshot 2022-05-26 at 2 43 07 AM" src="https://user-images.githubusercontent.com/5299907/170369194-3c1969f9-4233-4350-a557-212929a9eb80.png">

If we look into [the picture attached originally with this issue](https://user-images.githubusercontent.com/5299907/170223552-f7d63b1d-d14a-47f8-9a7b-90bac786fb5c.png), requirement is not to cut it into 2 parts around 180th meridian but draw a straight line. Any possible way to achieve that ?

**Comment by Pessimistress** [comment] 2022-05-25 22:09
https://deck.gl/docs/api-reference/core/map-view#repeat

Closing since this is not a bug. Please use Discussion if you need further help with your use case.

**Closed by Pessimistress** 2022-05-25 22:09 UTC
Labels: bug

**Comment by mnhkahn** [comment] 2024-08-21 10:04
> @Pessimistress https://codepen.io/andycool/pen/ExQbbeG?editors=001

This code works for me!
