### ISSUE TITLE
GeoJsonLayer does not fill extremely large polygons from d3 correctly.

### ISSUE THREAD

**Issue by tech-meppem** [visgl/deck.gl#5533] opened 2021-02-25 10:54 UTC
#### Description
When trying to draw large geojson polygons, the fill breaks when the polygons wrap around the map.

I am generating a circle from d3, using d3.geoCircle. When the circle is very large, the fill of the polygon breaks.

The circle is centred on lng: -96, lat: 40. I have hooked the radius of the circle to a slider, so on slider change, it will change the circle radius (calls the genRadiusLayer function). However, this breaks when the circle/polygon wraps around the map/poles.

![deck map not filling to corners 2](https://user-images.githubusercontent.com/54634811/109141103-40eafe80-7755-11eb-8e68-1fd7d3d0058b.gif)

#### Expected Behavior
I would expect the fill to expand out the the corners of the map, instead of just joining together directly.
I have drawn over some screenshots of where I expect the fill would be, where it would fill the blue area:

![Screenshot_53](https://user-images.githubusercontent.com/54634811/109141636-dbe3d880-7755-11eb-83f5-fa22fd49d6dd.png)
![Screenshot_54](https://user-images.githubusercontent.com/54634811/109142659-0aae7e80-7757-11eb-8308-f2b82a7c5720.png)

#### Repro Steps

I am using OrthographicView to render the map, however, I did try with MapView, and it still breaks in a very similar way.

```
this.deckLayers.unshift(
          new deck.GeoJsonLayer({
            id: 'base-map',
            data: mapData,
            stroked: true,
            filled: true,
            lineWidthUnits: 'meters',
            lineWidthMinPixels: 0,
            lineWidthMaxPixels: 1,
            opacity: 0.08,
            getLineColor: stroke_color.toArray(),
            getFillColor: map_color.toArray(),
          })
        );
this.deckOut = new deck.Deck({
          views: new deck.OrthographicView({
            flipY: false,
            minZoom: 1,
            maxZoom: 10,
            controller: {
              inertia: 500
            }
          }),
          canvas: canvas,
          initialViewState: INITIAL_VIEW_STATE,
          layers: this.deckLayers,
        });

    addLayer: function(layer){
        const newLayers = Array.isArray(layer) ? layer : [layer];
        const existingLayers = this.deckLayers;
        for(let i = 0; i < existingLayers.length; i++){
          const exist = existingLayers[i];
          //going backwards to splice out of array
          for(let ii = newLayers.length - 1; ii >= 0; ii--){
            const newLayer = newLayers[ii];
            if(newLayer.id === exist.id){
              existingLayers[i] = newLayer;
              newLayers.splice(ii,1);
            }
          }
        }
        this.deckLayers = existingLayers.concat(newLayers);
        if(this.deckOut){
          this.deckOut.setProps({layers: this.deckLayers});
        }
      },

    genRadiusLayer(){
        if(!this.distance || !this.home) return;
        //reverse because it's stored as [lat,lng]
        const centre = this.home.slice().reverse();
        const radius = rad_to_deg(this.distance / world_radius);;


        const circleData = d3.geoCircle()
          .precision(1.5)
          .center(centre)
          .radius(radius);

        const radialColor = new Color(this.getComputedStyleValue("--primary-color")).setVal(51,3);
        const radialStrokeColor = radialColor.clone().setVal(255,3);

        const circleGeoJSON = circleData();
        circleGeoJSON.properties = {
          radius: radius,
          lng: centre[0],
          lat: centre[1]
        }

        console.log("circle",centre,radius,circleGeoJSON.coordinates)

        const radiusLayer = new deck.GeoJsonLayer({
          id: 'radial',
          coordinateSystem: deck.COORDINATE_SYSTEM.LNGLAT,
          data: circleGeoJSON,
          stroked: true,
          filled: true,
          lineWidthUnits: 'meters',
          lineWidthMinPixels: 2,
          lineWidthMaxPixels: 5,
          opacity: this.showRadial ? 1 : 0,
          getLineColor: radialStrokeColor.toArray(true),
          getFillColor: radialColor.toArray(true),
          dataComparator: (newData, oldData) => {
            return newData.properties.radius === oldData.properties.radius && newData.properties.lng === oldData.properties.lng && newData.properties.lat === oldData.properties.lat;
          }
        });
        this.addLayer([radiusLayer]);
      }
```

geoJson for map: https://gist.github.com/tech-meppem/0fff9cc0147b992406e579607533f42e

#### Environment
 - Framework Version: deck.gl 8.4.0, d3 5.12.0
 - Browser Version: Chrome Version 88.0.4324.182 (Official Build) (64-bit)
 - OS: Windows 10

**Comment by padawannn** [comment] 2021-02-25 11:46
@tech-meppem I think that the behavior you expect is not how a map library should behave. I have done a quick test generating a large circle with `d3.geoCircle` and I have tested the result on https://geojson.io and on Mapbox and the behavior is the same: 

- geojson.io: 
<img width="1090" alt="Captura de pantalla 2021-02-25 a las 12 38 47" src="https://user-images.githubusercontent.com/7164554/109149009-4b15f880-7767-11eb-8436-eb1968e10a64.png">

- Mapbox:
<img width="1909" alt="Captura de pantalla 2021-02-25 a las 12 38 56" src="https://user-images.githubusercontent.com/7164554/109149027-4fdaac80-7767-11eb-95a5-23463c42cdd5.png">

**Comment by tech-meppem** [comment] 2021-02-25 12:16
@padawannn However, if you switch to a globe view, then the circle is correct, as the circle is filled over the north pole. The circle wraps around the north pole completely, and geoJson io and mapbox both render it incorrectly.
![deck map not filling to corners globe](https://user-images.githubusercontent.com/54634811/109152256-26b81d00-7763-11eb-8b14-cf738f230859.gif)

**Comment by padawannn** [comment] 2021-02-25 13:31
But you are comparing two things that are totally different. The first case is a Web Mercator projection that is a flat representation of the earth. The second is a 3D projection of the earth. It's a bit difficult to explain in an issue the limitations of a flat representation. For better understanding, you can draw the polygon that d3.geoCircle returns in a tool like Qgis and ask it to show you all vertices of the polygon. The result you will get will be this:

<img width="1430" alt="Captura de pantalla 2021-02-25 a las 14 28 19" src="https://user-images.githubusercontent.com/7164554/109160171-bf579880-7775-11eb-8d95-3e2bb486e61d.png">

Each of the purple circles is the coordinate that makes up your "circle"

**Comment by padawannn** [comment] 2021-02-25 13:37
Another example for you to understand better:
In the case of the globe, when the circle is very large try to imagine that you flatten it for a 2D representation, the red surface would go out of the limits of the earth

**Comment by tech-meppem** [comment] 2021-02-25 13:56
I understand they are different projections, which is why I'm saying the fill is wrong.
The curve of the circle is correct, but the "inside" of the circle would be everything above the line (in this case).
The curve on the right is filling the "outside" of the circle.

![image](https://user-images.githubusercontent.com/54634811/109163234-02fbd380-7771-11eb-80cb-1996a6a8f0a7.png)

If it was to fill the circle, it would look like this (I manually inserted the corners of the map into the circle):
![image](https://user-images.githubusercontent.com/54634811/109163349-2888dd00-7771-11eb-97e9-b6c9d48d0dad.png)

**Comment by padawannn** [comment] 2021-02-25 15:22
Ok, I will attach another image for better understanding. Forget that you have a circle, in the end, what you are representing is a set of vertices that represent a polygon. If I remove the fill and leave only the edges of the polygon we get this:

<img width="1001" alt="Captura de pantalla 2021-02-25 a las 15 57 16" src="https://user-images.githubusercontent.com/7164554/109171541-2c712b00-7782-11eb-9c8a-af47d3c62095.png">

How would you fill this? Indeed, to get the behavior that you want, you have to add two other vertices resulting in a different polygon.

Keep in mind that all the screenshots that I am attaching are made with other tools such as Qgis so you can see that it is not a deck.gl bug. You can try the same geojson in any geospatial tool or library and you will get the same result.

**Comment by Pessimistress** [comment] 2021-02-25 16:22
There are several issues involved here:
- when you generate a circle that covers more than half of the earth, it is identical to its inverse. There is nothing in the GeoJSON specification for you to differentiate the two. Therefore it is unreasonable to ask the layer to fill the larger one.
- there is a prop `wrapLongitude: true` in GeoJsonLayer that you can enable to [split the GeoJSON by geospatial bounds](https://deck.gl/docs/api-reference/core/layer#wraplongitude). This prop is currently not enabled by default in MapView for backward compatibility reasons, but you definitely have to enable it manually if you are using a non-geospatial view.

**Comment by Pessimistress** [comment] 2021-02-25 16:29
@padawannn Correctness aside, it seems that deck.gl does not fill one of the halves by default, which is consistent with Mapbox's behavior. Under the hood, we use Mapbox's `earcut` to tesselate polygons.

**Comment by Pessimistress** [comment] 2021-03-01 14:46
@tech-meppem can you confirm that `wrapLongitude: true` solves your issue?

**Comment by tech-meppem** [comment] 2021-03-01 18:00
@Pessimistress Sorry, no it doesn't. (also sorry for not replying sooner, I finally solved it though)
I have been able to solve my problems, here's the gist for anyone else who wants it:
https://gist.github.com/tech-meppem/3e2d35eab93d27182bebc824b13407ad

**Comment by Pessimistress** [comment] 2021-03-02 02:27
> no it doesn't

Without further elaboration, I am closing this issue as there is no verified bug in the GeoJsonLayer. Adding the `wrapLongitude` prop does render large GeoJSON features correctly as you illustrated in your original comment (expected behavior case 1), which you can verify with my Codepen link above. But apparently, that's not sufficient to cover your use case, probably due to your need to fill a circle larger than half of the earth's surface, which is really a limitation in GeoJSON itself.

**Closed by Pessimistress** 2021-03-02 02:27 UTC
Labels: bug
