### ISSUE TITLE
[Bug]keep updating GeoJsonLayer 20 times, the CPU will reach 100%

### ISSUE THREAD

**Issue by oishi4multisoup** [visgl/deck.gl#8742] opened 2024-04-02 02:19 UTC
### Description

Our system is a system that handles architectural drawings.
It is necessary to update the layer every time you switch floors, and the information is also updated automatically.

keep updating GeoJsonLayer 20 times, the CPU will reach 100%
each GeoJson file size is from 1.6MB to 13MB
The browser freezes when the CPU reaches 100%.

```
  layers.value = renderLayers()
  deckgl.value.setProps({
    initialViewState: getViewState(),
    layers: layers.value
  })
```

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Steps to Reproduce

keep updating GeoJsonLayer 20 times over
or 
leave the screen alone

### Environment

- Framework version: deck.gl@8.9.35 / vue@3.4.21
- Browser: Chrome 123.0.6312.87（Official Build） （arm64）
- OS: macOS Sonoma 14.4.1

### Logs

<img width="960" alt="image" src="https://github.com/visgl/deck.gl/assets/53546430/cd0f1f67-7102-4edb-b4cb-1fe1db54a97c">

**Comment by Pessimistress** [comment] 2024-04-02 03:46
Please provide a functional code snippet and dataset that reproduces your issue.

**Comment by oishi4multisoup** [comment] 2024-04-02 04:23
I'm sorry.
The drawings are confidential and cannot be made public.
The source for generating and updating GeoJsonLayer is as follows.

```
// Generating GeoJsonLayer
const drawing = new GeoJsonLayer({
    id: 'drawing',
    data: selectedDrawing.value,
    bounds: selectedDrawingBounds.value,
    coordinateSystem: COORDINATE_SYSTEM.CARTESIAN,
    target: [0, 0, 0],
    getLineColor: [128, 128, 128],
    stroked: true,
    filled: false,
    pickable: false
  })

// Update Layer
layers.value = renderLayers()
  deckgl.value.setProps({
    initialViewState: getViewState(),
    layers: layers.value
  })

```

**Comment by Pessimistress** [comment] 2024-04-02 04:29
Your bug report states that the steps to reproduce is simply "keep updating GeoJsonLayer 20 times." If that is true, then you should be able to reproduce the issue with ANY GeoJSON. If you cannot reproduce it with a public dataset, then the issue is specific to your own data.

As you can see we have over 100 bugs open right now. Any work you do to help us confirm the bug will get your issues resolved faster.

**Comment by oishi4multisoup** [comment] 2024-04-02 04:51
I’ll create a sample using a large-sized GeoJson that is publicly available, so please give me some time.

**Comment by Pessimistress** [comment] 2024-04-02 05:43
I don't know what the `layers,value`/`deckgl.value` are in your code, but it looks like you are using deck.gl with some framework or state management library. Some of these things, like Vue, are known to recursively modify bound data props, in which case it's not surprising that you are getting problems with a large nested object such as GeoJSON. I highly recommend you use the Chrome profiler to find out what function is using that CPU time before rushing to conclusions.

**Comment by oishi4multisoup** [comment] 2024-04-02 06:36
As you said, I'm using Vue 3.

**Comment by Pessimistress** [comment] 2024-04-02 09:27
This is a known problem for Vue in general. Putting a large complex object into the reactivity system is expensive and unnecessary.

[markRaw](https://vuejs.org/api/reactivity-advanced.html#markraw)

> Some values simply should not be made reactive, for example a complex 3rd party class instance, or a Vue component object.

**Comment by Pessimistress** [comment] 2024-04-02 09:29
Closing this issue unless reproduceable in standalone deck.gl.

**Closed by Pessimistress** 2024-04-02 09:29 UTC
Labels: bug

**Comment by oishi4multisoup** [comment] 2024-04-02 09:33
There was a slight improvement by changing ref to shallowRef, so it may not be a problem with Deck.gl. We will close it.

**Comment by oishi4multisoup** [comment] 2024-04-02 09:34
Thanks!
