### ISSUE TITLE
[Bug] Tile3DLayer disappearing problem in FirstPersonView

### ISSUE THREAD

**Issue by aybond** [visgl/deck.gl#6919] opened 2022-05-18 17:22 UTC
### Description

I've encountered a problem with Tile3DLayer tiles disappearing intermittently when using FirstPersonView mode. 
As I approach the layer objects on the map, the tiles appear disappear and then appear again.

Reference for a live example: https://replit.com/@aybond/deckgl-Tile3DLayer-disappearing-problem-in-FirstPersonView#index.html

P. S. The example does not use the latest version of deck.gl, as the latest version additionally has a problem with flickering layers. Read more about it here: https://github.com/visgl/loaders.gl/issues/1384#issuecomment-1129216681

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

Tile3DLayer tiles do not disappear in FirstPersonView mode.

### Steps to Reproduce

https://replit.com/@aybond/deckgl-Tile3DLayer-disappearing-problem-in-FirstPersonView#index.html

https://user-images.githubusercontent.com/6682452/169104963-9d01cf93-2799-4531-b859-2e893d396c0d.mov

### Environment

- Framework version: all
- Browser: Chrome 100.0
- OS: Ubuntu 20.04

**Comment by belom88** [comment] 2022-05-20 14:57
Can't reproduce it

https://user-images.githubusercontent.com/18549629/169555462-7f71518f-2174-4d85-af5c-b7e46aad682c.mp4

**Comment by aybond** [comment] 2022-05-20 16:52
Hello @belom88

In order to reproduce, you have to move towards the objects at a slight pitch.

P. S. I have decreased the height of the camera in the live example and now it is not necessary to approach at an angle, just move forward: https://replit.com/@aybond/deckgl-Tile3DLayer-disappearing-problem-in-FirstPersonView#index.html

**Comment by Radik24** [comment] 2022-06-14 07:27
Hello,

For me it's combined with https://github.com/visgl/deck.gl/issues/6555 (Point clouds).

I tried it with cesium 3d tiles, point clouds, i3s and it always disappears or flickers.

**Comment by belom88** [comment] 2022-07-08 11:45
There is a different behavior of `cullingVolume` calculation:
https://github.com/visgl/loaders.gl/blob/1801ec04b050222e92d8dc480b30462083e59b3c/modules/tiles/src/tileset/helpers/frame-state.ts#L134
For the FirstPersonView expression `plane.distance - distanceToCenter` returns close to 0 values that scales normal to 0 here:
https://github.com/visgl/loaders.gl/blob/1801ec04b050222e92d8dc480b30462083e59b3c/modules/tiles/src/tileset/helpers/frame-state.ts#L143
`console.log(`${dir} - ${plane.distance - distanceToCenter}`);` for `FirstPersonView`:
```
frame-state.ts:138 ============================
frame-state.ts:142 left - -1.4210854715202004e-14
frame-state.ts:142 right - 2.842170943040401e-14
frame-state.ts:142 bottom - 0
frame-state.ts:142 top - 0
frame-state.ts:142 near - -0.000002054916421911912
frame-state.ts:142 far - 0.2054916419498909
frame-state.ts:160 ============================
frame-state.ts:138 ============================
frame-state.ts:142 left - -1.4210854715202004e-14
frame-state.ts:142 right - 2.842170943040401e-14
frame-state.ts:142 bottom - 5.684341886080802e-14
frame-state.ts:142 top - 0
frame-state.ts:142 near - -0.000002054916421911912
frame-state.ts:142 far - 0.205491642874847
frame-state.ts:160 ============================
frame-state.ts:138 ============================
frame-state.ts:142 left - -1.4210854715202004e-14
frame-state.ts:142 right - 2.842170943040401e-14
frame-state.ts:142 bottom - -5.684341886080802e-14
frame-state.ts:142 top - 2.842170943040401e-14
frame-state.ts:142 near - -0.000002054916421911912
frame-state.ts:142 far - 0.2054916424507951
frame-state.ts:160 ============================
```
The tile will disappear if `(plane.distance - distanceToCenter) === 0` at least for one plane.

The corresponding `console.log(`${dir} - ${plane.distance - distanceToCenter}`);` for `MapView`:
```
frame-state.ts:138 ============================
frame-state.ts:142 left - 0.010350767685473272
frame-state.ts:142 right - 0.010350767685565643
frame-state.ts:142 bottom - 0.0037208548171179245
frame-state.ts:142 top - 0.003720854817061081
frame-state.ts:142 near - 0.010981950993766532
frame-state.ts:142 far - 0.01883341651335968
frame-state.ts:160 ============================
frame-state.ts:138 ============================
frame-state.ts:142 left - 0.013031266907852057
frame-state.ts:142 right - 0.013031266907887584
frame-state.ts:142 bottom - 0.00468443053887313
frame-state.ts:142 top - 0.004684430538901552
frame-state.ts:142 near - 0.01382590537411943
frame-state.ts:142 far - 0.023710635271896763
frame-state.ts:160 ============================
frame-state.ts:138 ============================
frame-state.ts:142 left - 0.016405924892062274
frame-state.ts:142 right - 0.01640592489206938
frame-state.ts:142 bottom - 0.00589753982677621
frame-state.ts:142 top - 0.005897539826833054
frame-state.ts:142 near - 0.017406347881347983
frame-state.ts:142 far - 0.0298508889550817
frame-state.ts:160 ============================
```

**Comment by Pessimistress** [comment] 2022-07-11 22:28
Well the calculation should not depend on `viewport.center`. In `FirstPersonView` `center` is the vanishing point, so the distance from it to the frustum planes are always 0 (or very close).

There is no reason to do

```js
const distanceToCenter = plane.normal.dot(viewport.center);
scratchPosition
      .copy(plane.normal)
      .scale(plane.distance - distanceToCenter)
      .add(viewport.center);
```

while you can just do

```js
scratchPosition
      .copy(plane.normal)
      .scale(plane.distance)
```

**Comment by belom88** [comment] 2022-07-12 15:42
Frustum culling doesn't work with it. It loads all available tiles.
It is possibly because of `viewportCenterCartesian` that also calculated from `viewport.center`

**Comment by Pessimistress** [comment] 2022-07-12 15:57
I see. Instead of calculating it from `viewport.center` you should use the common origin `[0,0,0]`.

**Comment by Pessimistress** [comment] 2022-07-29 14:55
A bug fix has been published in loaders.gl v3.2.6. Please give it a try by removing your lock file and reinstall dependencies.

**Comment by aybond** [comment] 2022-08-04 15:20
> A bug fix has been published in loaders.gl v3.2.6. Please give it a try by removing your lock file and reinstall dependencies.

Solved for my use case. Thnx!

**Closed** 2022-08-04 17:59 UTC
Labels: bug

**Comment by Radik24** [comment] 2022-08-11 08:25
Sorry for late reply, I tested it little bit after release and it seemed to be fine! Thanks
