### ISSUE TITLE
CartoBQTilerLayer visualization breaks after a while

### ISSUE THREAD

**Issue by martejpad** [visgl/deck.gl#5340] opened 2021-01-15 20:46 UTC
#### Description

We are using CartoBQTilerLayer in a tileset viewer application and found that the visualization breaks after a while:

You can access the visualization [here](https://viewer.carto.com/user/ernestomb/bigquery?config=eyJkZXNjcmlwdGlvbiI6IkNhcnRvQlFUaWxlckxheWVyIGRlY2xhcmF0aXZlIGV4YW1wbGUiLCJpbml0aWFsVmlld1N0YXRlIjp7ImxhdGl0dWRlIjo1Mi43NDc3ODAzMTYzOTU5MywibG9uZ2l0dWRlIjotMTA3Ljk0MzExNTU0NDg3MDIxLCJ6b29tIjoyLjc0OTQyNjMxNjAyMjAwOCwicGl0Y2giOjAsImJlYXJpbmciOjAsImRyYWdSb3RhdGUiOmZhbHNlLCJ3aWR0aCI6ODY0LCJoZWlnaHQiOjc4MiwiYWx0aXR1ZGUiOjEuNSwibWF4Wm9vbSI6MjAsIm1pblpvb20iOjAsIm1heFBpdGNoIjo2MCwibWluUGl0Y2giOjAsInRyYW5zaXRpb25EdXJhdGlvbiI6MH0sInZpZXdzIjpbeyJAQHR5cGUiOiJNYXBWaWV3IiwiY29udHJvbGxlciI6dHJ1ZSwibWFwU3R5bGUiOiJAQCNDQVJUT19CQVNFTUFQLlBPU0lUUk9OIn1dLCJsYXllcnMiOlt7IkBAdHlwZSI6IkNhcnRvQlFUaWxlckxheWVyIiwiZGF0YSI6ImRvLXB1YmxpYy10aWxlc2V0LnVzYV9hY3MuZGVtb2dyYXBoaWNzX3NvY2lvZGVtb2dyYXBoaWNzX3VzYV9ibG9ja2dyb3VwXzIwMTVfNXlyc18yMDEzMjAxNyIsImNyZWRlbnRpYWxzIjp7InVzZXJuYW1lIjoiZXJuZXN0b21iIiwiYXBpS2V5IjoiZGVmYXVsdF9wdWJsaWMifSwiZ2V0RmlsbENvbG9yIjp7IkBAZnVuY3Rpb24iOiJjb2xvckJpbnMiLCJhdHRyIjoidG90YWxfcG9wIiwiZG9tYWluIjpbNzI5LDkzNywxMTU0LDEzOTQsMTcxMiwyMjM1XSwiY29sb3JzIjoiVGVtcHMifSwicG9pbnRSYWRpdXNNaW5QaXhlbHMiOjIsInN0cm9rZWQiOmZhbHNlLCJwaWNrYWJsZSI6dHJ1ZX1dfQ%3D%3D).

I have reproduced the error with two different tilesets and from different computers (all MacOS).

![image](https://user-images.githubusercontent.com/23744137/104776065-be484a00-5779-11eb-96c8-13f1133bbb27.png)

#### Repro Steps
- Open the visualization.
- Keep your browser tab open and unbothered for a while (minutes). It does not have to be in the foreground.
- Come back to the visualization and change the zoom level.

#### Environment
 - Framework Version: deck.gl 8.4.0-alpha.4
 - Browser Version: Chrome Version 87.0.4280.88
 - OS: Mac OS X 10.15.6

#### Logs
No errors or warnings in the console.

**Comment by ilan-gold** [comment] 2021-01-17 03:01
What exactly "breaks?" Does this page crash or is it locked and you can't change zoom levels?

**Comment by martejpad** [comment] 2021-01-17 10:42
HI @ilan-gold, thanks for your reply! The visualization should look like this (i.e. without all those strange lines):

![image](https://user-images.githubusercontent.com/23744137/104838032-adeab900-58b8-11eb-8d7a-e94dd7145d90.png)

You can have a more detailed look in [the link](https://viewer.carto.com/user/ernestomb/bigquery?config=eyJkZXNjcmlwdGlvbiI6IkNhcnRvQlFUaWxlckxheWVyIGRlY2xhcmF0aXZlIGV4YW1wbGUiLCJpbml0aWFsVmlld1N0YXRlIjp7ImxhdGl0dWRlIjo1Mi43NDc3ODAzMTYzOTU5MywibG9uZ2l0dWRlIjotMTA3Ljk0MzExNTU0NDg3MDIxLCJ6b29tIjoyLjc0OTQyNjMxNjAyMjAwOCwicGl0Y2giOjAsImJlYXJpbmciOjAsImRyYWdSb3RhdGUiOmZhbHNlLCJ3aWR0aCI6ODY0LCJoZWlnaHQiOjc4MiwiYWx0aXR1ZGUiOjEuNSwibWF4Wm9vbSI6MjAsIm1pblpvb20iOjAsIm1heFBpdGNoIjo2MCwibWluUGl0Y2giOjAsInRyYW5zaXRpb25EdXJhdGlvbiI6MH0sInZpZXdzIjpbeyJAQHR5cGUiOiJNYXBWaWV3IiwiY29udHJvbGxlciI6dHJ1ZSwibWFwU3R5bGUiOiJAQCNDQVJUT19CQVNFTUFQLlBPU0lUUk9OIn1dLCJsYXllcnMiOlt7IkBAdHlwZSI6IkNhcnRvQlFUaWxlckxheWVyIiwiZGF0YSI6ImRvLXB1YmxpYy10aWxlc2V0LnVzYV9hY3MuZGVtb2dyYXBoaWNzX3NvY2lvZGVtb2dyYXBoaWNzX3VzYV9ibG9ja2dyb3VwXzIwMTVfNXlyc18yMDEzMjAxNyIsImNyZWRlbnRpYWxzIjp7InVzZXJuYW1lIjoiZXJuZXN0b21iIiwiYXBpS2V5IjoiZGVmYXVsdF9wdWJsaWMifSwiZ2V0RmlsbENvbG9yIjp7IkBAZnVuY3Rpb24iOiJjb2xvckJpbnMiLCJhdHRyIjoidG90YWxfcG9wIiwiZG9tYWluIjpbNzI5LDkzNywxMTU0LDEzOTQsMTcxMiwyMjM1XSwiY29sb3JzIjoiVGVtcHMifSwicG9pbnRSYWRpdXNNaW5QaXhlbHMiOjIsInN0cm9rZWQiOmZhbHNlLCJwaWNrYWJsZSI6dHJ1ZX1dfQ%3D%3D) I included in the issue-

**Comment by ilan-gold** [comment] 2021-01-17 21:39
Sorry @martejpad, that totally slipped by me!

**Comment by AdriSolid** [comment] 2021-01-19 14:12
@martejpad Could you check in another browser and let us know? Maybe it's a hardware-related problem..

Couldn't reproduce the error, environment:
- Chrome Version: 87.0.4280.66
- Firefox Version: 84.0
- OS: Ubuntu 20.04

**Comment by padawannn** [comment] 2021-04-12 12:03
I think that it's happening because of a bug on the viewer of Carto dashboard. It's fixed now. Can you confirm it?

**Comment by alasarr** [comment] 2021-04-22 18:54
Fixed now.

**Comment by martejpad** [comment] 2021-07-01 12:16
Hi! I'm reopening this one as this issue as the problem seems to be back...

I have been able to find the exact steps to reproduce it using Chrome. Doesn't seem to happen in other browsers (tried Firefox and Safari).

1. Open [this](https://public.carto.com/viewer/user/public/bigquery?config=eyJpbml0aWFsVmlld1N0YXRlIjp7ImxhdGl0dWRlIjo1MS43MjkxMTQyMTU3MTc3ODYsImxvbmdpdHVkZSI6LTExMy4zNDMyNDYyMzczNzU2OCwiem9vbSI6Mi42NzA4NDMxMDU3MDAyNCwicGl0Y2giOjAsImJlYXJpbmciOjAsImRyYWdSb3RhdGUiOmZhbHNlLCJ3aWR0aCI6ODY0LCJoZWlnaHQiOjc4MiwiYWx0aXR1ZGUiOjEuNSwibWF4Wm9vbSI6MjAsIm1pblpvb20iOjAsIm1heFBpdGNoIjo2MCwibWluUGl0Y2giOjAsInRyYW5zaXRpb25EdXJhdGlvbiI6MCwidHJhbnNpdGlvbkludGVycnVwdGlvbiI6MX0sInZpZXdzIjpbeyJAQHR5cGUiOiJNYXBWaWV3IiwiY29udHJvbGxlciI6dHJ1ZSwibWFwU3R5bGUiOiJAQCNDQVJUT19CQVNFTUFQLkRBUktfTUFUVEVSIn1dLCJsYXllcnMiOlt7IkBAdHlwZSI6IkNhcnRvQlFUaWxlckxheWVyIiwiZGF0YSI6ImNhcnRvLWRvLXB1YmxpYy10aWxlc2V0cy51c2FfYWNzLmRlbW9ncmFwaGljc19zb2Npb2RlbW9ncmFwaGljc191c2FfYmxvY2tncm91cF8yMDE1XzV5cnNfMjAxNDIwMThfdGlsZXNldF8wMDEiLCJjcmVkZW50aWFscyI6eyJ1c2VybmFtZSI6InB1YmxpYyIsImFwaUtleSI6ImRlZmF1bHRfcHVibGljIn0sImdldEZpbGxDb2xvciI6eyJAQGZ1bmN0aW9uIjoiY29sb3JCaW5zIiwiYXR0ciI6Im1lZGlhbl9pbmNvbWUiLCJkb21haW4iOlszNzI2MSw1MDkzOCw2NTAwMCw4ODcwNF0sImNvbG9ycyI6IlRlYWxHcm4ifSwicG9pbnRSYWRpdXNNaW5QaXhlbHMiOjIsInN0cm9rZWQiOmZhbHNlLCJsaW5lV2lkdGhNaW5QaXhlbHMiOjEsImdldExpbmVDb2xvciI6WzI1NSwwLDI1NV0sInBpY2thYmxlIjp0cnVlLCJiaW5hcnkiOnRydWV9XX0%3D) tileset
2. Open [this page](https://carto.com/spatial-data-catalog/browser/dataset/acs_sociodemogr_95c726f9/) (which has a Deck.gl map)
3. Go back to the tileset tab. Move the map.

Thanks in advance!

**Comment by Pessimistress** [comment] 2022-02-23 19:10
I believe this is the same issue as #6649. Please track progress in the other thread.

**Closed by Pessimistress** 2022-02-23 19:10 UTC
Labels: bug
