### ISSUE TITLE
GeoJsonLayer doesn't support COORDINATE_SYSTEM.METER_OFFSETS

### ISSUE THREAD

**Issue by romanIlyushin-bc** [visgl/deck.gl#5433] opened 2021-02-04 18:54 UTC
#### Description
When I use meter coordinates and specify
coordinateSystem: COORDINATE_SYSTEM.METER_OFFSETS 
param for my GeoJson layer, it doesn't display anything.

#### Expected Behavior
Layer should support METER_OFFSETS param or clearly state in the doc about inability to support it.

#### Repro Steps
See above

#### Environment
 - Framework Version: deck.gl 8.3.0
 - Browser Version: Chrome 88.0
 - OS: Mac OS X 10.15.7

#### Logs
No console error messages

**Comment by Pessimistress** [comment] 2021-02-04 18:56
`GeoJsonLayer` does support METER_OFFSETS. If you think there is a bug, you need to provide the data and layer props that you are using to reproduce it.

**Comment by Pessimistress** [comment] 2021-02-11 16:55
Closing - cannot reproduce

**Closed by Pessimistress** 2021-02-11 16:55 UTC
Labels: bug
