### ISSUE TITLE
[Bug] MapboxLayer doesn't respect `visible` prop for layers

### ISSUE THREAD

**Issue by jessekrubin** [visgl/deck.gl#6651] opened 2022-02-15 20:16 UTC
### Description

I am not able to toggle layer visibility when using a MapboxLayer. 

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

I expect the MapboxLayer to not render layers when `visibile: false`

### Steps to Reproduce

Here is a snippet. There is more setup at the bottom including setting the deckgl instance and the map instance. 

I am using the latest version of `react-map-gl` (`^7.0.0`)

```
import * as React from 'react';
// @ts-ignore
import { ArcLayer } from 'deck.gl';
// @ts-ignore
import { Deck } from '@deck.gl/core';
// @ts-ignore
import { MapboxLayer } from '@deck.gl/mapbox';
import { Map } from 'react-map-gl';

const TOKEN = ''

const INIT_VIEW_STATE = {
  longitude: -122.45,
  latitude: 37.75,
  zoom: 11,
  bearing: 0,
  pitch: 60
}
export default function App() {
  const mapRef = React.useRef();
  const deckRef = React.useRef();

  const [layervisible, setLayervisible] = React.useState(true);
  const arcLayer: ArcLayer = new ArcLayer({
    id: "arclayer",
    data: 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/bart-segments.json',
    getSourcePosition: d => d.from.coordinates,
    getTargetPosition: d => d.to.coordinates,
    getSourceColor: [255, 200, 0],
    getTargetColor: [0, 140, 255],
    getWidth: 12,
    visible: layervisible
  });

  return (
    <>
      <button onClick={() => {
        setLayervisible(!layervisible)
        console.log(layervisible)
      }}>toggle-visible</button>
      <Map
        id="p2map"
        mapStyle="mapbox://styles/mapbox/light-v9" 
        mapboxAccessToken={TOKEN}
        style={
          {
            width: '1200px',
            height: '800px',
          }
        }
        onLoad={(map) => {
          // @ts-ignore
          mapRef.current = map.target
          console.log(map.target)
          deckRef.current = new Deck({

            // @ts-ignore
            gl: mapRef.current.painter.context.gl,
            layers: [arcLayer]
          })
          map.target.addLayer(
            new MapboxLayer({ id: "deckgl", deck: deckRef.current })
          )
        }}
        initialViewState={INIT_VIEW_STATE}
      >
      </Map>
    </>
  );
}
```

### Environment

- Framework version:
- Browser: chrome/firefox
- OS: Windows and ubuntu (wsl)

**Comment by Pessimistress** [comment] 2022-02-15 22:28
We cannot reproduce the issue from the code you provided. Please create a Codepen/CodeSandbox.

**Comment by jessekrubin** [comment] 2022-02-16 02:16
@Pessimistress I have updated the og-issue to be a full example. I find codepen/codesandbox annoying, so if you want a more full repro, I would rather do that via a bug-repo. Is the updated code good enough for you to repro? 

I have found ways to toggle the deck layers, but I am unable to toggle the deck layers by changing their `visible` bool val. Would be nice to be able to do that and would save me a crap ton of code-writing.

**Comment by Pessimistress** [comment] 2022-02-16 02:47
You only set the layer once in Map's `onLoad` callback. The layer's `visible` value is whatever `layervisible` is when the callback is called.

Closing since this is not a bug in the library. Go to Discussions if you need help understanding how to use MapboxLayer.

**Closed** 2022-02-16 02:47 UTC
Labels: bug
