### ISSUE TITLE
[maplibre] checkerboard rendering regression when `interleaved: true`

### ISSUE THREAD

**Issue by chrisgervang** [visgl/deck.gl#8602] opened 2024-03-07 19:17 UTC
I'm noticing a rendering issue in Maplibre GL JS when deck renders into its WebGL context (`interleaved: true`). The tiles aren't rendering correctly, they "checkerboard" while navigating. 

This issue appears to only effect Maplibre v3 & Deck v9. I've tested and found no issue with Mapbox GL JS v3 & Deck v9, or with either basemap lib in Deck v8.9. Note that I can't test Maplibre v2 or v1 since Deck v9 requires WebGL2 for interleave.

Reproduction: https://codesandbox.io/p/sandbox/deck-v9-maplibre-interleave-repro-8602-lzx4z8?file=%2Findex.html%3A8%2C54

https://github.com/visgl/deck.gl/assets/2461547/6f8b9500-2c70-4d17-b7ee-c92fc6cd4d18

_Originally posted by @chrisgervang in https://github.com/visgl/deck.gl/issues/8551#issuecomment-1984254002_

**Comment by chrisgervang** [comment] 2024-03-13 22:45
@donmccurdy @felixpalmer @Pessimistress any idea what causes this regression?

**Comment by donmccurdy** [comment] 2024-03-14 00:49
I'll try testing tomorrow, but this looks similar to the issues fixed by https://github.com/visgl/luma.gl/pull/2032.

**Comment by donmccurdy** [comment] 2024-03-14 19:24
Seems not to have been resolved by the earlier fix. Possibly a depth buffer issue. I've started a branch and copied the repro case into an example for testing...

https://github.com/visgl/deck.gl/compare/donmccurdy/fix-maplibre-interleave

... will see where I can get on a fix there!

**Comment by chrisgervang** [comment] 2024-03-14 20:25
Thanks! You can also use https://github.com/visgl/deck.gl/tree/master/test/apps/mapbox-integration

**Comment by chrisgervang** [comment] 2024-03-26 15:57
Hey @birkskyum and @HarelM, we're so far unable to track down the cause of this rendering issue with deck v9 and maplibre. We aren't noticing it with other base maps. Do know anyone who could help us resolve this? Your help is much appreciated!

**Comment by HarelM** [comment] 2024-03-26 16:37
Can you clarify what the issue is?
The statement about v3 not working while v3 works is probably the root cause.
Also we've released version 4 of maplibre.
Let me know how I can help.

**Comment by chrisgervang** [comment] 2024-03-26 16:46
Did you notice the checkerboard rendering artifacts in the video or Codesandbox? That only seems to happen in Maplibre. I'll try Maplibre 4. Also to clarify, interleaved rendering (shared context) works without artifacts in Mapbox (and Google maps) but not Maplibre.

**Comment by HarelM** [comment] 2024-03-26 16:52
I'm guessing it is related to "fighting z order", but my expertise here are limited when it comes to webgl context stuff...

**Comment by birkskyum** [comment] 2024-03-26 16:53
I wonder if we have a different depth buffer precision than the other base maps.

**Comment by birkskyum** [comment] 2024-03-26 17:14
This is surely z-fighting
<img width="709" alt="Screenshot 2024-03-26 at 18 02 12" src="https://github.com/visgl/deck.gl/assets/74932975/0b9fc4cb-a57d-4680-be3d-ef164333ad45">

I can trace the introduction of the error to the first v9 alpha 3. This error isn't present with deck.gl v8, and maplibre gl js v4/latest. What happened in this initial v9 work?

**Comment by birkskyum** [comment] 2024-03-26 17:46
**For the issue introduced in 9.0.0-beta.6**

This could very well come as a result of bumping luma.gl from 9.0.0-beta.4 to 9.0.0-beta.6, which cuts away webgl1 support entirely, as mentioned here.
- https://github.com/visgl/deck.gl/pull/8567

It's maybe not the only thing, but I do see a mention to "Use device.createTexture instead of WEBGLRenderBuffer". I believe MapLibre LG JS still use the WEBGLRenderBuffer here:
- https://github.com/maplibre/maplibre-gl-js/blob/c91d7fb60adc05ac3a357b03cbab2ef63d4cda23/src/gl/value.ts#L369-L380

Updating these places, potentially by introducing more conditional webgl1/2 logic, or going all in on webgl2 like deck.gl/mapbox, might help on these types of issues.

**Comment by ibgreen** [comment] 2024-03-26 21:35
>  I believe MapLibre LG JS still use the WEBGLRenderBuffer here:

Good observation, worth some thought... But I can't think of a reason why creating and binding a `Renderbuffer` with the WebGL 2 API outside of the luma.gl API would cause problems. 

There is no deep motivation behind the renderbuffer removal in v9. It just didn't seem worth the trouble to expose Renderbuffers through the luma.gl v9 Texture API  - since it seems that textures can be used in all cases that required Renderbuffers in WebGL 1, and I could not find clear information stating that there are convincing perf advantages to renderbuffers.

**Comment by arthurgailes** [comment] 2024-04-23 18:46
I'm also having this issue via MapboxOverlay when interleaving since updating to deckgl v9/mapbox v3

**Comment by arthurgailes** [comment] 2024-04-23 19:05
> I'm also having this issue via MapboxOverlay when interleaving since updating to deckgl v9/mapbox v3

Repro works when using mapbox basemap: [Codesandbox](https://codesandbox.io/p/sandbox/deck-v9-maplibre-interleave-repro-8602-forked-m2nsjy?file=%2Findex.html%3A39%2C13&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvcqn08g00072a6bef6enlh6%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvcqn08g00032a6bls2m29r7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvcqn08g00042a6b9iywsch1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvcqn08g00062a6bf8w3f1za%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvcqn08g00032a6bls2m29r7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvcqn08g00022a6bimbe8md7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A39%252C%2522startColumn%2522%253A13%252C%2522endLineNumber%2522%253A39%252C%2522endColumn%2522%253A13%257D%255D%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvcqn08g00032a6bls2m29r7%2522%252C%2522activeTabId%2522%253A%2522clvcqn08g00022a6bimbe8md7%2522%257D%252C%2522clvcqn08g00062a6bf8w3f1za%2522%253A%257B%2522id%2522%253A%2522clvcqn08g00062a6bf8w3f1za%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvcqn08g00052a6b0g999o38%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvcqn08g00052a6b0g999o38%2522%257D%252C%2522clvcqn08g00042a6b9iywsch1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvcqn08g00042a6b9iywsch1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

![image](https://github.com/visgl/deck.gl/assets/29307425/06b852be-d4bb-4798-bbfe-359ebf65294c)

**Comment by ibgreen** [comment] 2024-04-23 19:13
- Looks like basic z-fighting. 
- You could try to set `getPolygonOffset` prop on the PolygonLayer to fix it in the app. 
- Wonder why this is a regression... it does look like deck should apply a minimal offset to all layers in interleaved mode.

**Comment by chrisgervang** [comment] 2024-04-23 19:19
These layers (e.g. roads) are native basemap layers though, so I don't think there is a PolygonLayer to apply props to, unless there's a maplibre equivalent.

**Comment by arthurgailes** [comment] 2024-04-23 19:42
Just noting that the problem is present in both mapboxgl v2 and v3, but not in deck 8.9.

**Comment by ibgreen** [comment] 2024-04-23 19:47
> I don't think there is a PolygonLayer to apply props to

Sorry, I meant the ScatterplotLayer. And to be clear, I was talking about making a change in the linked codesandbox. I was going to try to but it seemed read-only.

```
      const deckOverlay = new MapboxOverlay({
        interleaved: true,
        layers: [
          new ScatterplotLayer({
            id: "deckgl-circle",
            beforeId: "water",
            data: [
              { position: [-122.402, 37.79], color: [255, 0, 0], radius: 1000 },
            ],
            getPosition: (d) => d.position,
            getFillColor: (d) => d.color,
            getRadius: (d) => d.radius,
            opacity: 0.3,
          }),
          new ArcLayer({
            id: "deckgl-arc",
            data: [
              {
                source: [-122.3998664, 37.7883697],
                target: [-122.400068, 37.7900503],
              },
            ],
            getSourcePosition: (d) => d.source,
            getTargetPosition: (d) => d.target,
            getSourceColor: [255, 208, 0],
            getTargetColor: [0, 128, 255],
            getWidth: 8,
          }),
        ],
      });
```

**Comment by birkskyum** [comment] 2024-04-23 20:37
@chrisgervang , that's interesting - I can think of some places that likely will be problematic as a result of some missing webgl2 extensions. Things like the [maplibre heatmap layer](https://maplibre.org/maplibre-gl-js/docs/examples/heatmap-layer/) come to mind.

**Comment by ibgreen** [comment] 2024-04-23 20:42
>  likely will be problematic as a result of some missing webgl2 extensions

I assume you are referring to the fact that WebGL2 contexts are not allowed to support WebGL1 extensions that offer functionality that is built-in to WebGL2. It would probably not be hard to make shims for those extensions if you had a list. After all the reason they are removed is that the functionality is already supported in the core, so we just need to override `context.getExtension()` and return some objects that forward calls to the new context methods.

**Comment by birkskyum** [comment] 2024-04-23 20:54
All conditional loading of extensions is contained here:
https://github.com/maplibre/maplibre-gl-js/blob/main/src/gl/context.ts

And a single VAO check here:
https://github.com/maplibre/maplibre-gl-js/blob/main/src/gl/value.ts#L429-L433

**Comment by ibgreen** [comment] 2024-04-24 18:38
> All conditional loading of extensions is contained here:

I looked and realized your code handles both WebGL1 and WebGL2 with dynamic checks so you should not have any issues as far as I can tell, even if we force feed you a WebGL2 context.

**Comment by birkskyum** [comment] 2024-04-24 18:47
It does that from v3, but it didn't do that in maplibre gl js v2 which @chrisgervang mentioned.

**Closed** 2024-04-26 21:00 UTC
Labels: bug
