### ISSUE TITLE
[bug] H3HexagonLayer in the Mapbox example renders random pink hexagons

### ISSUE THREAD

**Issue by chrisgervang** [visgl/deck.gl#8606] opened 2024-03-07 20:24 UTC
The `H3HexagonLayer` in the Mapbox website example renders random pink hexagons. In testing, this first appeared with #8572, which was first released in `9.0.0-beta.6`.

Reproduction Steps:
1. Checkout `master`
2. ```
    yarn bootstrap
    cd examples/website/mapbox
    yarn
    yan start-local
    ```

![Screen Shot 2024-03-07 at 11 22 05 AM](https://github.com/visgl/deck.gl/assets/2461547/2480e3f6-da8f-4f00-9ba6-dc819072c20a)

_Originally posted by @chrisgervang in https://github.com/visgl/deck.gl/issues/8582#issuecomment-1984335817_

**Comment by donmccurdy** [comment] 2024-03-13 21:13
I'm not able to reproduce this now, appears to be fixed by https://github.com/visgl/deck.gl/pull/8631.

**Closed by donmccurdy** 2024-03-13 21:13 UTC
Labels: bug
