### ISSUE TITLE
[Feat] Composite Layers over terrain.

### ISSUE THREAD

**Issue by alienatorZ** [visgl/deck.gl#7346] opened 2022-10-19 18:40 UTC
### Target Use Case

This would help when wanting to visualize a TileLayer draped over the terrain. This would allow composite layers to be draped as well.

### Proposal

Currently the prop is similar to `texture: 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/terrain-mask.png',`.
This only allows one url to work on the terrain.

I would be better to follow the Deck way of having a `layers:[]` then all the layers in the array are draped over the terrain.

**Comment by Pessimistress** [comment] 2022-10-19 18:45
Duplicate of #7195

**Closed by Pessimistress** 2022-10-19 18:45 UTC
Labels: feature
