### ISSUE TITLE
Picking Info doesn't work on mobile (iOS)

### ISSUE THREAD

**Issue by jarekpelczynski** [visgl/deck.gl#2646] opened 2019-01-31 12:39 UTC
I've upgraded to deck.gl and luma.gl 6.4 and picking info doesn't work, object is `null`. Tested on Simulator and iPhone.

Any of these examples don't work: http://deck.gl/#/documentation/developer-guide/adding-interactivity?section=using-pure-js
Same as an example: http://deck.gl/#/examples/core-layers/icon-layer

The issue appears also under 6.3.x

**Comment by ibgreen** [comment] 2019-01-31 14:34
> I've upgraded to deck.gl and luma.gl 6.4 and picking info doesn't work... The issue appears also under 6.3.x

@jarekpelczynski Just to clarify, has it ever worked for you on iOS? I.e. are you reporting a regression or a bug? If it has worked, which version was good?

**Comment by jarekpelczynski** [comment] 2019-01-31 14:48
Yes, It worked under 6.1.1 and earlier, under 5.x for sure.

**Comment by jianhuang01** [comment] 2019-01-31 18:15
![img_3696](https://user-images.githubusercontent.com/15093546/52075416-12cc6d80-2541-11e9-8498-3b74633bdff3.PNG)
![img_3698](https://user-images.githubusercontent.com/15093546/52075417-12cc6d80-2541-11e9-850d-5b84d3e0efba.PNG)
Tested and can't reproduce, the picking works well on my iphone 6s

**Comment by jarekpelczynski** [comment] 2019-02-01 07:39
@jianhuang01 I can't find the first example – mind you provide the URL?

The second example works for me. 
I checked version:
```
deck
{VERSION: "untranspiled source", version: "untranspiled source", log: e}
luma
{VERSION: "6.4.0-alpha.3", version: "6.4.0-alpha.3", log: e, stats: {…}, globals: {…}}
```
but the example with [Meteorites Landings](http://deck.gl/#/examples/core-layers/icon-layer) an event doesn't trigger.

**Comment by jianhuang01** [comment] 2019-02-01 14:56
@jarekpelczynski here is the [URL](http://deck.gl/#/documentation/deckgl-api-reference/layers/icon-layer), the Meteorites Landings example is down on mobile, we will check the website issue, the picking module in deck.gl should be fine.

**Comment by jarekpelczynski** [comment] 2019-03-14 15:44
I get these errors when I click on the layer (Safari/iOS simulator).
![error](https://api.monosnap.com/rpc/file/download?id=w2WfRtbRBTbcB4PTnfkXx3qP3hmE4n)
and also `onClick` on image layer doesn't trigger.

Those errors could be related to this issue?

**Comment by tsherif** [comment] 2019-03-14 17:34
Looks like the texture it's creating for the framebuffer is too large. 

@ibgreen is the `devicePixelRatio` option new in Luma?

@jarekpelczynski can you go to this site and tell us what it reports for your `Max Texture Size`: http://webglreport.com/

**Comment by ibgreen** [comment] 2019-03-14 17:44
> @ibgreen is the devicePixelRatio option new in Luma?

No it is not. 

However it seems every year, new phone models have more extreme retina resolutions (I think they are now 400dpi+, certainly beyond what my eyes can resolve), so we are taking a big memory and performance hit without much visible gain.

I always felt that `useDevicePixels` should default to `false` on mobile devices.

**Comment by tsherif** [comment] 2019-03-14 17:46
> I always felt that useDevicePixels should default to false on mobile devices.

Maybe everywhere? Could be considered a "high quality rendering" option for users that want it, with the performance caveats made clear.

**Comment by jarekpelczynski** [comment] 2019-03-14 17:46
@tsherif WebGLReports shows 4096

**Comment by tsherif** [comment] 2019-03-14 17:56
@jarekpelczynski yeah, that's pretty tight. Do you know what the resolution of your screen is?

**Comment by ibgreen** [comment] 2019-03-14 18:02
> Maybe everywhere? Could be considered a "high quality rendering" option for users that want it, with the performance caveats made clear.

Perhaps. It certainly improves visuals on MacBooks which is our main user base and perf is good in the applications that are most important to us, so removing it by default would be a step down for these users unless all apps started to opt in.

The issue I have seen is mainly when folks connect 4K external displays, and/or use this on mobile phones.

Alternatively, as a crazy idea: with all the instrumentation you are putting in, we could support an `auto` mode where device pixels would be turned off if FPS fell too much.

**Comment by jarekpelczynski** [comment] 2019-03-14 18:02
@tsherif I use iOS Simulator and iPhone Xs device so it should be 2436 x 1125px. I try to figure out why picking object doesn't work on iOS devices and got these errors with framebuffers

**Comment by Pessimistress** [comment] 2020-10-16 17:51
Closing since this discussion was about a very old version of deck.gl. Reopen if this is still an issue with the latest release.

**Closed by Pessimistress** 2020-10-16 17:51 UTC
Labels: bug
