### ISSUE TITLE
composite layer with sub layer props "pickable: true" flush when map viewport change

### ISSUE THREAD

**Issue by mahdijirofti** [visgl/deck.gl#4852] opened 2020-08-06 18:25 UTC
I have a composite layer like below.
when I set pickable to false in both scatterplot layer and path layer everything works fine but when pickable is true in both or just one of sublayer composite layer disappear when map viewport changes.

Note that I know pickable limitations in performance but I test with just one line and point.

MY ISSUE:

![outputwww](https://user-images.githubusercontent.com/22638025/89567712-5808e400-d837-11ea-9816-e4c318f067b5.gif)

MY CODE: 
```
import { CompositeLayer, PathLayer, ScatterplotLayer } from 'deck.gl';
import { colorToRGBArray } from '../utils';

class MyLineLayer extends CompositeLayer {
	updateState({ props, changeFlags }) {
		if (changeFlags.dataChanged) {
			const scatterLayerData = [];
			// line data format:
			//  [
			// 	 {
			// 	 		shape: [[-122.45, 37.78],...],
			// 	 		stops: [
			// 	 			{name: '12-road', coordinate: {lat: -122.23, lng: 35.234}},
			// 	 			{name: '13-road', coordinate: {lat: -122.23, lng: 35.234}}
			// 	 		]
			// 	 },
			// 	  {
			// 	 		shape: [[-122.45, 37.78],...],
			// 	 		stops: [
			// 	 			{name: '14-road', coordinate: {lat: -122.23, lng: 35.234}},
			// 	 			{name: '15-road', coordinate: {lat: -122.23, lng: 35.234}}
			// 	 		]
			// 	 },
			// 	 ...
			//  ]
			//  data format to pass to scatterLayer:
			//  [
			// 	 {name: '12-road', coordinate: {lat: -122.23, lng: 35.234}},
			// 	 {name: '13-road', coordinate: {lat: -122.23, lng: 35.234}},
			// 	 {name: '14-road', coordinate: {lat: -122.23, lng: 35.234}},
			// 	 {name: '15-road', coordinate: {lat: -122.23, lng: 35.234}},
			// 	 ...
			//  ]

			props.data.forEach((line, index) => {
				for (let i = 0, len = line.stops.length; i < len; i++) {
					const stop = line.stops[i];
					scatterLayerData.push(
						this.getSubLayerRow(
							{
								stop,
							},
							line,
							index,
						),
					);
				}
			});

			this.setState({ scatterLayerData });
		}
	}

	renderLayers() {
		const { data, getPath, getColor, getWidth, getRadius } = this.props;
		const { scatterLayerData } = this.state;
		return [
			new PathLayer(
				this.getSubLayerProps({
					id: 'path',
					data,
					pickable: true,
					widthScale: 2,
					widthMaxPixels: 8,
					widthMinPixels: 4,
					getPath,
					getColor,
					getWidth,
					rounded: true,
				}),
			),
			new ScatterplotLayer(
				this.getSubLayerProps({
					data: scatterLayerData,
					id: 'scatter-layer',
					pickable: true,
					opacity: 1,
					stroked: true,
					filled: true,
					getFillColor: [255, 255, 255],
					radiusScale: 2,
					radiusMinPixels: 4,
					radiusMaxPixels: 40,
					getPosition: d => [d.stop.coordinate.lng, d.stop.coordinate.lat],
					getRadius,
					lineWidthMaxPixels: 16,
					lineWidthMinPixels: 2,
					lineWidthScale: 9,
					getLineColor: this.getSubLayerAccessor(getColor),
				}),
			),
		];
	}
}

MyLineLayer.layerName = 'MyLineLayer';

MyLineLayer.defaultProps = {
	// PATH LAYER
	getPath: { type: 'accessor', value: d => d.shape },
	getColor: { type: 'accessor', value: d => colorToRGBArray(d.color) },
	getWidth: { type: 'accessor', value: 1 },
	// SCATTER LAYER
	getRadius: { type: 'accessor', value: 6 },
};

export default MyLineLayer;

```

**Comment by Pessimistress** [comment] 2020-08-06 19:06
Do you see any console errors?

**Comment by mahdijirofti** [comment] 2020-08-07 09:16
@Pessimistress 
No there was no error on my console.
I set console.log() every time My composite layer construct and every time composite layer updateLayer function invoke then I see just one log of each console.log, therefore, I think there is no bug on my side.

Surprisingly, when I restart my computer after many hours of working on my code everything works fine and I can't reproduce this bug.
I'm using Chrome 79.0 on Ubuntu 18.04.
Do you have any idea about that?
Is it possible it is something like a memory leak in WebGL?

**Comment by Pessimistress** [comment] 2020-10-28 14:49
Closing because were unable to reproduce the bug. Reopen if you see this again.

**Closed by Pessimistress** 2020-10-28 14:49 UTC
Labels: question
