### ISSUE TITLE
[Bug] Layers incorrectly clipped when using interleaved maps with beforeId

### ISSUE THREAD

**Issue by bwswedberg** [visgl/deck.gl#6541] opened 2021-12-29 13:08 UTC
### Description

Layer rendering order is not honored when using the [interleaved approach](https://deck.gl/docs/get-started/using-with-map) with the `beforeId` param for some deckgl layers. This causes those layers to be appear clipped when they should be "above" the others.

`GeoJsonLayer` seems to work as expected with the `beforeId`. However, `ScatterplotLayer` appears to be clipped by `GeoJsonLayer`s that should be below them. I've attached a [codesandbox](https://codesandbox.io/s/wizardly-bhaskara-vixrw?file=/app.js) to demo this. It is setup same as [here](https://deck.gl/docs/api-reference/mapbox/overview).

**Screenshot of bug**
![image](https://user-images.githubusercontent.com/7384136/147663105-9ce738e9-bd8a-4e97-ac54-4c559e9880c1.png)

I believe this issue may not just be related to `ScatterplotLayer` + `GeoJsonLayer` combo because I've noticed the below. I did not provide codesandboxes for these because I'm guessing it's related to the same issue.
- `HeatmapLayer` will clip `ScatterplotLayer` similar to how GeoJsonLayer clips it
- `TileLayer` (like in the [example](https://deck.gl/docs/api-reference/geo-layers/tile-layer)) gets clipped by `GeoJsonLayer` and `HeatmapLayer` similar to `ScatterplotLayer`

### Flavors

- [X] React
- [ ] Python/Jupyter notebook
- [X] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

The expected behavior is for all deck.gl layers to honor the `beforeId` associated with `map.addLayer(MapboxLayer, <beforeId>)`. Right now `ScatterplotLayer` and possibly other layers get clipped by layers below them.

**Expected**
![image](https://user-images.githubusercontent.com/7384136/147663301-96e46130-d6dc-478e-847d-783b2c03de8e.png)
This is what I believe the map should render given the layer order as specified by the `beforeId` params. The above image was produced by swapping in`GeoJsonLayer` for the `ScatterplotLayer` the codesandbox.

### Steps to Reproduce

https://codesandbox.io/s/wizardly-bhaskara-vixrw?file=/app.js

### Environment

- Framework version: deck.gl@8.3.0
- Browser: Chrome 95.0.4638.69
- OS: iOS 12.0.1 

### Logs

None

**Comment by Pessimistress** [comment] 2021-12-29 17:03
Duplicate of #6284

**Comment by bwswedberg** [comment] 2021-12-29 17:55
Thank you!!! Apologies for missing that in the issue tracker.

**Comment by Pessimistress** [comment] 2022-01-19 18:28
Fixed in v8.6.6

**Closed by Pessimistress** 2022-01-19 18:28 UTC
Labels: bug
