### ISSUE TITLE
`rounded: true` not work in Trips Layer

### ISSUE THREAD

**Issue by Kaiyiwing** [visgl/deck.gl#5747] opened 2021-05-10 12:19 UTC
#### Description

if I set `rounded` to  `true`, should the head of trip line also be rouned?
But it's not work, it's a bug or feature?
![image](https://user-images.githubusercontent.com/44634134/117658075-e77b6300-b1cc-11eb-8176-212308f72c5b.png)

#### Expected Behavior

the head of trip line should be rounded.

#### Repro Steps

https://deck.gl/docs/api-reference/geo-layers/trips-layer

#### Environment
 - Framework Version: [e.g. deck.gl 8.3.0 / pydeck 0.5.0]
 - Browser Version: [e.g. Chrome 78.0]
 - OS: [e.g. Mac OS X 10.15 / iOS 14.2]

**Comment by Pessimistress** [comment] 2021-05-10 16:04
This is not something the TripsLayer supports. `rounded` makes the ends and joints round.

**Comment by Kaiyiwing** [comment] 2021-05-11 01:50
Thanks for your replay~
So,is there any way to make the head of trip line be rouned?

**Comment by Pessimistress** [comment] 2021-05-14 12:59
You can create a ScatterplotLayer to display a circle at the trail head. You will need to calculate and update the trail head position yourself based on the current time.

Closing this issue because it's not a bug.

**Closed by Pessimistress** 2021-05-14 12:59 UTC
