### ISSUE TITLE
ArcGIS layer to add 3DTile, drag the map, 3DTile model move

### ISSUE THREAD

**Issue by haitunxiaomo** [visgl/deck.gl#5901] opened 2021-06-22 03:31 UTC
#### Description
I wanted to load 3Dtile data in the ArcGIS scene. The data was loaded successfully, but when dragging the map, the data displayed would float.

https://user-images.githubusercontent.com/8519144/122858967-d0906a80-d34d-11eb-9823-9fbcba6fddfb.mp4

#### Expected Behavior
The data is displayed in the corresponding position, and the map drag does not move

#### Repro Steps
`// import React, {useState, useEffect} from 'react';
import {loadArcGISModules} from '@deck.gl/arcgis';
import {GeoJsonLayer, ArcLayer} from '@deck.gl/layers';
import {ScenegraphLayer} from '@deck.gl/mesh-layers';
import {CesiumIonLoader} from '@loaders.gl/3d-tiles';
import {Tile3DLayer,TripsLayer} from '@deck.gl/geo-layers';
import {AmbientLight, PointLight, LightingEffect} from '@deck.gl/core';

// source: Natural Earth http://www.naturalearthdata.com/ via geojson.xyz
const AIR_PORTS =
  'https://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_10m_airports.geojson';

loadArcGISModules(['esri/Map', 'esri/views/SceneView', 'esri/layers/SceneLayer','esri/views/3d/externalRenderers']).then(({DeckRenderer, modules}) => {
  const [ArcGISMap, SceneView, SceneLayer, externalRenderers] = modules;
  var sceneLayer = new SceneLayer({
	  portalItem: {
		id: "b343e14455fe45b98a2c20ebbceec0b0"
	  }
	});
  const mapView = new SceneView({
    container: 'viewDiv',
    map: new ArcGISMap({
      basemap: 'dark-gray-vector',
	  ground: "world-elevation",
      layers: [sceneLayer]
    }),
    center: [-122.4, 37.74],
    zoom: 11,
  });
  //sceneLayer.when(function(){
	  //mapView.extent = sceneLayer.fullExtent;
  //})
  mapView.map.ground.navigationConstraint = 'none';
  
  const layer = new ScenegraphLayer({
  id: 'ScenegraphLayer',
  data: 'https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/bart-stations.json',
  
  /* props from ScenegraphLayer class */
  
  _animations: {
    '*': {speed: 5}
  },
  _lighting: 'pbr',
  getOrientation: d => [0, Math.random() * 180, 90],
  getPosition: d => d.coordinates,
  scenegraph: 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxAnimated/glTF-Binary/BoxAnimated.glb',
  sizeScale: 500,
  pickable: true,
});

const ambientLight = new AmbientLight({
  color: [255, 255, 255],
  intensity: 1.0
});

const pointLight = new PointLight({
  color: [255, 255, 255],
  intensity: 2.0,
  position: [-74.05, 40.7, 8000]
});

const lightingEffect = new LightingEffect({ambientLight, pointLight});
const material = {
  ambient: 0.1,
  diffuse: 0.6,
  shininess: 32,
  specularColor: [60, 64, 70]
};

const DEFAULT_THEME = {
  buildingColor: [74, 80, 87],
  trailColor0: [253, 128, 93],
  trailColor1: [23, 184, 190],
  material,
  effects: [lightingEffect]
};

let theme = DEFAULT_THEME;

const tripsLayer = new TripsLayer({
  id: 'trips-layer',
  data:'https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/trips/trips-v7.json',
  // getPath: d => d.waypoints.map(p => p.coordinates),
  getPath: d => d.path,
  getTimestamps: d => d.timestamps,
  getColor: d => (d.vendor === 0 ? theme.trailColor0 : theme.trailColor1),
  opacity: 0.3,
  widthMinPixels: 2,
  rounded: true,
  trailLength:200,
  currentTime: 100,

  shadowEnabled: false
});
  const renderer = new DeckRenderer(mapView, {
    layers: [
		layer,
    tripsLayer
    ],
  });

  externalRenderers.add(mapView, renderer);
  
});
`

#### Environment
 - Framework Version: [e.g. deck.gl 8.3.0 / pydeck 0.5.0]
 - Browser Version: chrome 89.0.4389.82
 - OS: window 10  64

**Comment by Pessimistress** [comment] 2021-06-22 06:44
Duplicate of #5271

**Closed** 2021-06-22 06:44 UTC
Labels: bug

**Comment by haitunxiaomo** [comment] 2021-06-22 07:24
> Duplicate of #5271

Why move to 5271
