### ISSUE TITLE
PointCloudLayer picking doesn't work as expected when multiple points are stacked on top of each other

### ISSUE THREAD

**Issue by sfairgrieve** [visgl/deck.gl#4702] opened 2020-06-20 18:34 UTC
#### Description
PointCloudLayer picking works as expected except in cases where multiple points in the same/or very close location in 2D or 3D space are stacked on top of each other.  Hovering over a stacked set of points results in either no object being picked or the wrong object being picked.  I've tried throwing in my own call to `deck.pickMultipleObjects` with a greater `depth` just to see if that makes any difference, but it exhibits the same issues described previously.

One workaround I've considered is adding in my own code to prevent duplicate/close locations before passing data to the `PointCloudLayer`, but I'm wondering if there's a way to improve picking here.  Appreciate any insights you can provide.
  
#### Repro Steps
- Load data with duplicate lat/lon or lat/lon/alt points or very close lat/lon/alt points into a `PointCloudLayer` so that point cloud points are stacked on top of each other.
- Set the layer to be pickable
- Hover over a set of stacked points.

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8+
 - Browser Version: Chrome 83.0.4103.97
 - OS: Mac OS X 10.15.5

**Comment by Pessimistress** [comment] 2020-06-20 19:15
It is possible that picking does not work reliably if your points are smaller than one pixel. Does a bigger `pointSize` fix the problem?

Otherwise please create a codepen/code sandbox that reproduces this issue.

**Comment by sfairgrieve** [comment] 2020-06-20 19:25
I was originally using a `pointSize` of 5 and just tried with a value of 20 and see the same behavior.  I'll create a codepen and post the link shortly.  Appreciate your help.

**Comment by sfairgrieve** [comment] 2020-06-21 17:58
So in building a separate CodePen, I was to able to figure out specifically when this occurs, and it seems to be due to passing blending parameters with the layer.  In particular, I've been applying additive blending like so to give the layer a heatmap-like appearance when points are stacked on top of each other:

```
parameters: {
         [GL.BLEND]: true,
         [GL.BLEND_SRC_RGB]: GL.ONE,
         [GL.BLEND_DST_RGB]: GL.ONE,
         [GL.BLEND_EQUATION]: GL.FUNC_ADD
}
```

If I pass any of the `GL.BLEND_*` parameters, this appears to throw off picking even if `GL.BLEND` is set to false.  Here's a rough example:  https://codepen.io/sfairgrieve/pen/qBbrbKW.  On hovering, this will show an orange highlight over what deck.gl thinks is the picked object.

**Comment by Pessimistress** [comment] 2020-06-23 23:21
deck.gl is supposed to overwrite your parameters during picking. Because you are not using [luma.gl's parameter names](https://luma.gl/docs/api-reference/gltools/parameter-setting#blending), the merged parameters object contain conflicting settings.

Using the following parameters fixes the problem:

```js
parameters: {
        blend: true,
        blendFunc: [GL.ONE, GL.ONE],
        blendEquation: GL.FUNC_ADD
}
```

**Comment by sfairgrieve** [comment] 2020-06-23 23:52
Thanks @Pessimistress, that's super helpful!

**Closed** 2020-07-04 13:33 UTC
Labels: bug
