### ISSUE TITLE
[Bug] Picking with 3d layers seems to have errors

### ISSUE THREAD

**Issue by Lyeeedar** [visgl/deck.gl#7237] opened 2022-09-05 16:19 UTC
### Description

When using a geojson layer with _full3d (haven't tested if its broken with xyz data without _full3d) sometimes you cannot pick features when clicking towards the top of the feature. Clicking in the bottom section seems to work fine however.

I'm assuming there is some bug that stops the picking texture being fully rendered, maybe some sort of clipping based on z?

I was wondering if there is any way I can preview the picking texture, or otherwise debug that.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Steps to Reproduce

None as of yet.

### Environment

- Framework version:
- Browser:
- OS:

**Comment by Lyeeedar** [comment] 2022-09-06 11:28
Extracting a single feature into a test does not reproduce the bug, but it does happen with my full dataset (~1000 features).

**Comment by Pessimistress** [comment] 2022-12-06 10:13
Closing as duplicate of #7461

**Closed** 2022-12-06 10:13 UTC
Labels: bug
