### ISSUE TITLE
[Bug] H3 Cluster Layer get_fill_color bug

### ISSUE THREAD

**Issue by BartSu** [visgl/deck.gl#8375] opened 2024-01-02 10:53 UTC
### Description

https://pydeck.gl/gallery/h3_cluster_layer.html
https://deckgl.readthedocs.io/en/latest/gallery/h3_cluster_layer.html

![image](https://github.com/visgl/deck.gl/assets/23166423/9882adf4-fba7-4e0c-bd5d-8cb13547bdb3)
![image](https://github.com/visgl/deck.gl/assets/23166423/ff024f89-bdfd-480c-88cd-3932d28ae50f)

The same code above, the getFilledColor function does not work in latest version.

```
# Define a layer to display on a map
layer = pdk.Layer(
    "H3ClusterLayer",
    df,
    pickable=True,
    stroked=True,
    filled=True,
    extruded=False,
    get_hexagons="hexIds",
    get_fill_color="[255, (1 - mean / 500) * 255, 0]", # issue here
    get_line_color=[255, 255, 255],
    line_width_min_pixels=2,
)
```

### Flavors

- [ ] Script tag
- [ ] React
- [x] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

The latest version 'get_fill_color' function should work properly.

### Steps to Reproduce

https://pydeck.gl/gallery/h3_cluster_layer.html
https://deckgl.readthedocs.io/en/latest/gallery/h3_cluster_layer.html

### Environment

- Framework version: 8.9.33
- Browser: Chrome
- OS: MacOS 14.2.1 (23C71)

**Comment by Pessimistress** [comment] 2024-01-30 01:40
Duplicate of #7618?

**Closed** 2024-02-29 00:18 UTC
Labels: bug
